---
title: "Poursuite d'étude"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
knitr::opts_chunk$set(fig.asp=9/16, fig.retina = 2)


library(tidyverse)
library(ggthemes)
library(ggalluvial)

library(ggcpesrthemes)
theme_cpesr_setup(authors="Julien Gossa",
                  source="SIES <fr-esr-taux-poursuite-enseignement-superieur-par-academie")

spoilerTable <- function(df) {
  cat("\n<details>\n")
  cat("  <summary>Voir les données</summary>\n\n")
  
  print(kableExtra::kable(df, format="pipe"))
  
  cat("\n\n</details>\n")
}

pe <- read.csv2("../data/fr-esr-taux-poursuite-enseignement-superieur-par-academie.csv", dec='.') %>% 
  rename(
    Session = Rentrée...Session,
    Bacheliers = Nombre.total.de.bacheliers
  ) %>%
  mutate(
    Poursuivants.public = rowSums(.[c(5:12,17:18,23:24)]),
    Poursuivants.privé = rowSums(.[c(15:16,21:22)]),
    Poursuivants.nc = rowSums(.[c(13:14,19:20)])
    ) %>%
  mutate(Poursuivants = Poursuivants.public + Poursuivants.privé + Poursuivants.nc) %>%
  mutate(Session = as.character(Session)) %>%
  mutate(Série = factor(Série.du.bac, 
                        levels = c("Bac général","Bac technologique","Bac professionnel"),
                        labels = c("Gen.","Techno.","Pro.")))
```


https://data.enseignementsup-recherche.gouv.fr/explore/dataset/fr-esr-taux-poursuite-enseignement-superieur-par-academie/


```{r colnames}
colnames(pe)
```



```{r pe.all}
pe %>%
  group_by(Session = as.character(Session)) %>%
  summarise(across(c(starts_with("Néo")),sum)) %>% 
  pivot_longer(starts_with("Néo"), names_to = "Filière", values_to = "Poursuites") %>% 
  mutate(
    Secteur = case_when(
      str_detect(Filière,"secteur.privé") ~ "Privé",
      str_detect(Filière,"non.renseigné") ~ "NC",
      TRUE ~ "Public"),
    Mobilité = ifelse(str_detect(Filière,"différente"),"Hors académie", "Même académie")
  ) %>%
    mutate(Poursuite = paste(Secteur,Mobilité)) %>% 
  group_by(Session,Poursuite) %>%
  summarise(Poursuites = sum(Poursuites)) %>% 
  ggplot(aes(x=Session,y=Poursuites, group=Poursuite)) +
  geom_vline(xintercept = "2017") +
  geom_area(aes(fill=Poursuite,color=Poursuite), alpha=0.7, size=1) + 
  scale_color_brewer(palette = "Paired") +
  scale_fill_brewer(palette = "Paired") +
  theme_cpesr_cap() 
```

```{r pe.all.val100}
pe %>%
  group_by(Session = as.character(Session)) %>%
  summarise(across(c(Bacheliers,starts_with("Néo")),sum)) %>% 
  pivot_longer(starts_with("Néo"), names_to = "Filière", values_to = "Poursuites") %>% 
  mutate(
    Secteur = case_when(
      str_detect(Filière,"secteur.privé") ~ "Privé",
      str_detect(Filière,"non.renseigné") ~ "NC",
      TRUE ~ "Public"),
    Mobilité = ifelse(str_detect(Filière,"différente"),"Hors académie", "Même académie")
  ) %>%
  mutate(Poursuite = paste(Secteur,Mobilité)) %>% 
  group_by(Session,Secteur,Mobilité,Poursuite) %>%
  summarise(Poursuites = sum(Poursuites)) %>% 
  group_by(Secteur,Mobilité,Poursuite) %>%
  mutate(val100 = Poursuites / first(Poursuites) * 100) %>%
  ggplot(aes(x=Session,y=val100, group=1)) +
  geom_vline(xintercept = "2017") +
  geom_line(aes(fill=Poursuite,color=Poursuite), size=1) + 
  scale_color_brewer(palette = "Paired") +
  scale_fill_brewer(palette = "Paired") +
  facet_grid(Mobilité~Secteur) +
  theme_cpesr_cap() 
```


```{r pe.np, fig.retina=2}
pe %>%
  group_by(Session = as.character(Session), Série.du.bac) %>%
  summarise(Non.poursuivants = sum(Bacheliers - Poursuivants)/1000) %>% 
  ggplot(aes(x=Session,y=Non.poursuivants, group=Série.du.bac)) +
  geom_vline(xintercept = "2017") +
  geom_area(aes(fill=Série.du.bac,color=Série.du.bac), size=1, alpha = 0.6) + 
  scale_fill_discrete(name="") + 
  scale_color_discrete(name="") +
  ylab("Nombre de bacheliers\nnon poursuivants (milliers)") +
  theme_cpesr_cap() 
```

```{r pe.np.data, results='asis'}
pe %>%
  group_by(Session = as.character(Session), Série.du.bac) %>%
  summarise(Non.poursuivants = sum(Bacheliers - Poursuivants)) %>% 
  pivot_wider(names_from = Série.du.bac, values_from = Non.poursuivants) %>%
  spoilerTable()
```

```{r tpe}
pe %>%
  group_by(Session = as.character(Session)) %>%
  summarize(Taux.Poursuite.d.études = sum(Poursuivants,na.rm = TRUE) / sum(Bacheliers,na.rm = TRUE)) %>% 
  ggplot(aes(x=Session,y=Taux.Poursuite.d.études, group=1)) +
  geom_vline(xintercept = "2017") +
  geom_line(size=1) + geom_point(shape = 21, stroke=1, size=3, color = "white", fill="black") +
  theme_cpesr_cap()
```


```{r tpe.serie}
pe %>%
  group_by(Session = as.character(Session),Série.du.bac) %>%
  summarize(Taux.Poursuite.d.études = sum(Poursuivants,na.rm = TRUE) / sum(Bacheliers,na.rm = TRUE)) %>% 
  ggplot(aes(x=Session,y=Taux.Poursuite.d.études, group=Série.du.bac)) +
  geom_vline(xintercept = "2017") +
  geom_line(aes(color=Série.du.bac), size=1) + 
  geom_point(aes(fill=Série.du.bac), shape = 21, stroke=1, size=3, color = "white") +
  theme_cpesr_cap()
```


```{r tpe.serie.val100}
pe %>%
  group_by(Session = as.character(Session),Série.du.bac) %>%
  summarize(Taux.Poursuite.d.études = sum(Poursuivants,na.rm = TRUE) / sum(Bacheliers,na.rm = TRUE)) %>% 
  group_by(Série.du.bac) %>%
  mutate(val100 = Taux.Poursuite.d.études / first(Taux.Poursuite.d.études) *100) %>%
  ggplot(aes(x=Session,y=val100, group=Série.du.bac)) +
  geom_vline(xintercept = "2017") +
  geom_line(aes(color=Série.du.bac), size=1) + 
  geom_point(aes(fill=Série.du.bac), shape = 21, stroke=1, size=3, color = "white") +
  theme_cpesr_cap()
```



```{r tpe.secteur}
pe %>%
  select(-Poursuivants) %>%
  pivot_longer(c(Poursuivants.privé,Poursuivants.public), names_to = "Secteur", values_to = "Poursuivants") %>%
  group_by(Session = as.character(Session), Secteur) %>%
  summarize(Taux.Poursuite.d.études = sum(Poursuivants,na.rm = TRUE) / sum(Bacheliers,na.rm = TRUE)) %>% 
  ggplot(aes(x=Session,y=Taux.Poursuite.d.études, group=Secteur)) +
  geom_vline(xintercept = "2017") +
  geom_line(aes(color=Secteur), size=1) + 
  geom_point(aes(fill=Secteur), shape = 21, stroke=1, size=3, color = "white") +
  theme_cpesr_cap()
```


```{r tpe.secteur.val100}
pe %>%
  select(-Poursuivants) %>%
  pivot_longer(c(Poursuivants.privé,Poursuivants.public), names_to = "Secteur", values_to = "Poursuivants") %>%
  group_by(Session = as.character(Session), Secteur) %>%
  summarize(Taux.Poursuite.d.études = sum(Poursuivants,na.rm = TRUE) / sum(Bacheliers,na.rm = TRUE)) %>% 
  group_by(Secteur) %>%
  mutate(val100 = Taux.Poursuite.d.études / first(Taux.Poursuite.d.études) *100) %>%
  ggplot(aes(x=Session,y=val100, group=Secteur)) +
  geom_vline(xintercept = "2017") +
  geom_line(aes(color=Secteur), size=1) + 
  geom_point(aes(fill=Secteur), shape = 21, stroke=1, size=3, color = "white") +
  theme_cpesr_cap()
```





## Bacheliers

```{r bacheliers}
pe %>%
  group_by(Session = as.character(Session), Série.du.bac) %>%
  summarise(Bacheliers=sum(Bacheliers)/1000) %>% 
  ggplot(aes(x=Session,y=Bacheliers, group=Série.du.bac)) +
  geom_vline(xintercept = "2017") +
  geom_area(aes(fill=Série.du.bac,color=Série.du.bac), alpha=0.7, size=1) + 
  theme_cpesr_cap() 
```

```{r bacheliers.data, eval=FALSE}
pe %>%
  filter(Session %in% c("2010","2017","2020")) %>%
  group_by(Session, Série.du.bac) %>%
  summarise(Bacheliers=round(sum(Bacheliers)/1000)) %>% 
  group_by(Série.du.bac) %>%
  mutate(Evolution = scales::percent(Bacheliers / first(Bacheliers) - 1 )) %>%
  pivot_wider(names_from = Série.du.bac, values_from = c(Bacheliers,Evolution)) %>% 
  mutate(Total = `Bacheliers_Gen.`+`Bacheliers_Pro.`+`Bacheliers_Techno.`) %>%
  spoilerTable()
```

### Poursuites

```{r pe.all.data}
pe.pivot <- pe %>%
  group_by(Session,Série,Genre) %>%
  summarise(across(c(starts_with("Néo")),sum)) %>% 
  pivot_longer(starts_with("Néo"), names_to = "Label", values_to = "Poursuites") %>% 
  mutate(
    Secteur = factor(
      case_when(
        str_detect(Label,"secteur.privé") ~ "Privé",
        str_detect(Label,"non.renseigné") ~ as.character(NA),
        TRUE ~ "Public"),
      levels=c("Public","Privé","NC")),
    Mobilité = ifelse(str_detect(Label,"différente"),"Hors aca.", "Même aca."),
    Filière = factor(
      case_when(
        str_detect(Label,"université") ~ "Université",
        str_detect(Label,"en.IUT") ~ "IUT",
        str_detect(Label,"CPGE") ~ "CPGE",
        str_detect(Label,"STS") ~ "STS",
        TRUE ~ "Autre"),
      levels = c("Université","IUT","CPGE","STS","Autre"))
  )
```


```{r pe.pivot.fun}
pe_plot <- function(critere,palette="Set2") {
  pe.pivot %>%
    mutate(Critère = !!sym(critere)) %>%
    group_by(Session, Critère) %>%
    summarise(Poursuites = sum(Poursuites) / 1000) %>% 
    ggplot(aes(x=Session,y=Poursuites, group=Critère)) +
    geom_vline(xintercept = "2017") +
    geom_area(aes(fill=Critère,color=Critère), alpha=0.7, size=1, 
              position = position_stack(reverse = FALSE)) + 
    scale_color_brewer(palette = palette, name=critere, na.value = "grey50") +
    scale_fill_brewer(palette = palette, name=critere, na.value = "grey50") +
    #scale_y_continuous(labels=scales::percent) +
    ylab("Poursuites (milliers)") +
    scale_x_discrete(breaks=c("2010","2012","2014","2016","2018","2020")) +
    theme_cpesr() +
    theme(legend.position = "right")
}
```

```{r pe.criteres, fig.asp=9/16, fig.width=8}
cowplot::plot_grid(align = "hv", axis = "tblr",
  pe_plot("Série"), pe_plot("Filière"), pe_plot("Secteur"), pe_plot("Mobilité")
)
```

```{r pe.pivot.norm.fun}
pe_part_plot <- function(critere,palette="Set2") {
  pe.pivot %>%
    mutate(Critère = !!sym(critere)) %>%
    group_by(Session, Critère) %>%
    summarise(Poursuites = sum(Poursuites) / 1000) %>% 
    na.omit() %>%
    group_by(Session) %>%
    mutate(Part = Poursuites / sum(Poursuites)) %>%
    group_by(Critère) %>%
    mutate(Evol = Poursuites / first(Poursuites) * 100) %>%
    mutate(PartEvol = Part - first(Part)) %>%
    mutate(Session17 = relevel(factor(Session),"2017")) %>% 
    arrange(Session17) %>% 
    mutate(PartEvol17 = (Part - first(Part))*100) %>% 

    ggplot(aes(x=Session,y=PartEvol17, group=Critère)) +
      geom_vline(xintercept = "2017") +
      geom_line(aes(fill=Critère,color=Critère), size=1) + 
      scale_color_brewer(palette = palette, name=critere) +
      scale_fill_brewer(palette = palette, name=critere) +
      #scale_y_continuous(labels=scales::percent) +
      ylab("Part (valeur 100 en 2017)") +
      scale_x_discrete(breaks=c("2010","2012","2014","2016","2018","2020")) +
      theme_cpesr() +
      theme(legend.position = "right")
}

pe_part_plot("Secteur")
```

```{r pe.norm.criteres, fig.asp=9/16, fig.width=8}
cowplot::plot_grid(align = "hv", axis = "tblr",
  pe_part_plot("Série"), pe_part_plot("Filière"), pe_part_plot("Secteur"), pe_part_plot("Mobilité")
)
```

### Non poursuivants

```{r np.data}
np <- pe %>% 
  group_by(Session,Série,Genre,Académie.du.Bac) %>%
  summarize(Non.poursuites = sum(Bacheliers) - sum(Poursuivants))

np_plot <- function(critere,palette="Set2") {
  np %>%
    mutate(Critère = !!sym(critere)) %>%
    group_by(Session, Critère) %>%
    summarise(Non.poursuites = sum(Non.poursuites) / 1000) %>% 
    ggplot(aes(x=Session,y=Non.poursuites, group=Critère)) +
    geom_vline(xintercept = "2017") +
    geom_area(aes(fill=Critère,color=Critère), alpha=0.7, size=1, 
              position = position_stack(reverse = FALSE)) + 
    scale_color_brewer(palette = palette, name=critere) +
    scale_fill_brewer(palette = palette, name=critere) +
    #scale_y_continuous(labels=scales::percent) +
    ylab("Non poursuites (milliers)") +
    scale_x_discrete(breaks=c("2010","2012","2014","2016","2018","2020")) +
    theme_cpesr() +
    theme(legend.position = "right")
}

np_plot("Série")
np_plot("Genre")
```

```{r np.criteres, fig.asp=4.5/16, fig.width=8}
cowplot::plot_grid(align = "hv", axis = "tblr",
  np_plot("Série"), np_plot("Genre")
)
```
```{r np.norm.data}
np <- pe %>% 
  group_by(Session,Série,Genre,Académie.du.Bac) %>%
  summarize(Non.poursuites = sum(Bacheliers) - sum(Poursuivants))

np_norm_plot <- function(critere,palette="Set2") {
  np %>%
    mutate(Critère = !!sym(critere)) %>%
    group_by(Session, Critère) %>%
    summarise(Non.poursuites = sum(Non.poursuites) / 1000) %>% 
    group_by(Session) %>%
    mutate(Part = Non.poursuites / sum(Non.poursuites)) %>%
    group_by(Critère) %>%
    mutate(Evol = Non.poursuites / first(Non.poursuites) * 100) %>%
    mutate(PartEvol = Part - first(Part)) %>%
    mutate(Session17 = relevel(factor(Session),"2017")) %>% 
    arrange(Session17) %>% 
    mutate(PartEvol17 = (Part - first(Part))*100) %>% 
    na.omit() %>% 

    ggplot(aes(x=Session,y=PartEvol17, group=Critère)) +
    geom_vline(xintercept = "2017") +
    geom_line(aes(fill=Critère,color=Critère),  size=1) + 
    scale_color_brewer(palette = palette, name=critere) +
    scale_fill_brewer(palette = palette, name=critere) +
    #scale_y_continuous(labels=scales::percent) +
    ylab("Part dans les non poursuites (points p/r à 2017") +
    scale_x_discrete(breaks=c("2010","2012","2014","2016","2018","2020")) +
    theme_cpesr() +
    theme(legend.position = "right")
}

np_norm_plot("Série")
np_norm_plot("Genre")
```

```{r np.norm.criteres, fig.asp=4.5/16, fig.width=8}
cowplot::plot_grid(align = "hv", axis = "tblr",
  np_norm_plot("Série"), np_norm_plot("Genre")
)
```


### Flux Série / Filière

```{r flux}
pe.pivot %>% 
  group_by(Session,Série,Filière) %>%
  summarise(Poursuites = sum(Poursuites)) %>%
  group_by(Série,Filière) %>%
  mutate(Session17 = relevel(factor(Session),"2017")) %>% 
  arrange(Session17) %>% 
  mutate(Evolution = Poursuites / first(Poursuites) * 100 ) %>%
  ggplot(aes(x=Session,y=Evolution, color=Série, group=1)) +
  geom_vline(xintercept = "2017") +
  geom_line(size=1) +
  facet_grid(Série~Filière) +
  scale_x_discrete(breaks=c("2010","2017")) +
  ylab("Poursuites (valeur 100 en 2017)") +
  theme_cpesr()
```

```{r flux2}
pe.pivot %>% 
  group_by(Session,Série,Secteur,Filière) %>%
  summarise(Poursuites = sum(Poursuites)) %>%
  group_by(Série,Secteur,Filière) %>%
  na.omit() %>%
  mutate(Session17 = relevel(factor(Session),"2017")) %>% 
  arrange(Session17) %>% 
  mutate(Evolution = Poursuites / first(Poursuites) * 100 ) %>%
  ggplot(aes(x=Session,y=Evolution, color=Secteur, group=Secteur)) +
  geom_vline(xintercept = "2017") +
  geom_line(size=1) +
  facet_grid(Série~Filière) +
  scale_x_discrete(breaks=c("2010","2017")) +
  ylab("Poursuites (valeur 100 en 2017)") +
  theme_cpesr()
```

```{r flux2bis}
pe.pivot %>% 
  group_by(Session,Série,Filière) %>%
  summarise(Poursuites = sum(Poursuites)) %>%
  group_by(Série,Filière) %>%
  na.omit() %>%
  mutate(Session17 = relevel(factor(Session),"2017")) %>% 
  arrange(Session17) %>% 
  mutate(Evolution = Poursuites / first(Poursuites) * 100 ) %>%
  ggplot(aes(x=Session,y=Evolution, color=Série, group=Série)) +
  geom_vline(xintercept = "2017") +
  geom_line(size=1) +
  facet_grid(Série~Filière) +
  scale_x_discrete(breaks=c("2010","2017")) +
  ylab("Poursuites (valeur 100 en 2017)") +
  coord_cartesian(ylim=c(50,200)) +
  theme_cpesr()
```

```{r flux2ter}
pe.pivot %>% 
  group_by(Session,Série,Filière) %>%
  summarise(Poursuites = sum(Poursuites)) %>%
  #filter(Série != "Pro.", Filière != "Autre") %>%
  group_by(Série,Filière) %>%
  na.omit() %>%
  mutate(Session17 = relevel(factor(Session),"2017")) %>% 
  arrange(Session17) %>% 
  mutate(Evolution = Poursuites / first(Poursuites) * 100 ) %>%
  filter(Poursuites>5000) %>%
  ggplot(aes(x=Session,y=Evolution, color=Filière, group=Filière)) +
  geom_vline(xintercept = "2017") +
  geom_line(size=1) +
  geom_text(data=. %>% filter(Session == 2017), y=80, aes(label=round(Poursuites))) +
  facet_grid(Série~Filière) +
  scale_x_discrete(breaks=c("2010","2017")) +
  ylab("Poursuites (valeur 100 en 2017)") +
  theme_cpesr()
```

```{r flux2quatro}
pe.pivot %>% 
  group_by(Session,Série,Filière) %>%
  summarise(Poursuites = sum(Poursuites)) %>%
  #filter(Série != "Pro.", Filière != "Autre") %>%
  group_by(Série,Filière) %>%
  na.omit() %>%
  mutate(Session17 = relevel(factor(Session),"2017")) %>% 
  arrange(Session17) %>% 
  mutate(Evolution = Poursuites - first(Poursuites) ) %>%
  ggplot(aes(x=Session,y=Evolution, color=Filière, group=Filière)) +
  geom_vline(xintercept = "2017", size=0.2) +
  geom_line(size=1) +
  #geom_text(data=. %>% filter(Session == 2017), y=80, aes(label=round(Poursuites))) +
  facet_grid(Série~Filière) +
  scale_x_discrete(breaks=c("2010","2017")) +
  ylab("Poursuites (différence à 2017)") +
  theme_cpesr()
```

### Bac pro

```{r bp}
pe.pivot %>%
  filter(Série == "Pro.", Secteur == "Public", Filière == "Autre") %>% 
  group_by(Session,Série,Secteur,Filière) %>%
  summarise(Poursuites = sum(Poursuites)) %>%
  ggplot(aes(x=Session,y=Poursuites, color=Série, group=Série)) +
  geom_vline(xintercept = "2017") +
  geom_line(size=1) +
  scale_x_discrete(breaks=c("2010","2017")) +
  ylab("Poursuites") +
  theme_cpesr()
```


```{r bp2}
pe %>%
  filter(Série == "Pro.") %>% 
  group_by(Session,Académie.du.Bac) %>%
  summarise(Poursuites = sum(Néo.bacheliers.poursuivant.dans.une.autre.formation.du.secteur.public.dans.une.académie.différente.de.celle.d.obtention.de.leur.baccalauréat)) %>% 
  ggplot(aes(x=Session,y=Poursuites, color=Académie.du.Bac, group=Académie.du.Bac)) +
  geom_vline(xintercept = "2017") +
  geom_line(size=1) +
  scale_x_discrete(breaks=c("2010","2017")) +
  ylab("Poursuites") +
  theme_cpesr()
```


### Flux des différences


```{r diflux}
df <- pe.pivot %>%
  filter(Session %in% c("2017","2020")) %>%
  group_by(Session, Série, Filière) %>%
  summarise(Poursuites = sum(Poursuites)) %>%
  group_by(Série, Filière) %>%
  mutate(Diff = Poursuites - first(Poursuites)) %>%
  filter(Session == "2020") 

df 
df %>%
  filter(Diff > 0) %>%
  filter(Filière != "CPGE") %>%
ggplot(aes(y = Diff, axis1 = Série, axis2=Filière)) +
  geom_alluvium(aes(fill = Série, color=Série), width = 1/12, alpha=0.8) +
  geom_stratum(width = 1/6, fill = "black", color = "grey") +
  geom_text(stat = "stratum", color = "white", aes(label = after_stat(stratum))) +
  theme_cpesr() + theme(axis.text.x = element_blank())
```


```{r diflux2}
df <- pe.pivot %>%
  filter(Session %in% c("2017","2020")) %>%
  group_by(Session, Filière) %>%
  summarise(Poursuites = sum(Poursuites)) %>%
  group_by(Filière) %>%
  pivot_wider(values_from = Poursuites, names_from = Session, names_prefix = "Poursuites") %>%
  mutate(diff = Poursuites2020 - Poursuites2017) %>%
  mutate(Filière = as.character(Filière)) 

diflux <- bind_rows(
  transmute(df,
    id = paste("2017_",Filière),
    Session = "2017",
    Cohorte = "Bacheliers 2017",
    Filière = Filière,
    Effectif = Poursuites2017
  ),
  transmute(df,
    id = paste("2017_",Filière),
    Session = "2020",
    Cohorte = "Bacheliers 2017",
    Filière = Filière,
    Effectif = min(Poursuites2017,Poursuites2020)
  ),
  transmute(df,
    id = paste("2020_",Filière),
    Session = "2017",
    Cohorte = "Bacheliers 2020",
    Filière = "Bacheliers 2020",
    Effectif = -max(Poursuites2020-Poursuites2017,0)
    ),
  transmute(df,
    id = paste("2020_",Filière),
    Session = "2020",
    Cohorte = "Bacheliers 2020",
    Filière = Filière,
    Effectif = max(Poursuites2020-Poursuites2017,0)
    )
) %>%
  mutate(Filière = factor(Filière, 
                          levels = c("Université","IUT","CPGE","STS","Autre","Bacheliers 2020"))) %>%
  mutate(Effectif = Effectif / 1000)

  # ggplot(aes(y = Diff, axis1 = Série, axis2=Filière)) +
  # geom_alluvium(aes(fill = Série, color=Série), width = 1/12) +
  # geom_stratum(width = 1/12, fill = "black", color = "grey") +
  # geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  # theme_cpesr() + theme(axis.text.x = element_blank())

```

```{r diflux2plot}
diflux %>% 
  filter(Effectif != 0) %>%
  ggplot(aes(x=Session, y = Effectif, alluvium = id, stratum=Filière)) +
  geom_alluvium(aes(fill = Cohorte), color="white", width = 1/12, alpha=1) +
  geom_stratum(width = 1/6, fill = "black", color = "grey") +
  geom_text(stat = "stratum", color="white", aes(label = str_replace(after_stat(stratum)," ","\n"))) +
  scale_x_discrete(limits = c("2017", "2020"), expand = c(.1, .1)) +
  ylab("Poursuites (milliers)") +
  theme_cpesr()
```

```{r diflux3, fig.retina=2}
df.serie <- pe.pivot %>%
  filter(Session %in% c("2017","2020")) %>%
  group_by(Session, Série, Filière) %>%
  summarise(Poursuites = sum(Poursuites)) %>%
  group_by(Série, Filière) %>%
  pivot_wider(values_from = Poursuites, names_from = Session, names_prefix = "Poursuites") %>%
  mutate(diff = Poursuites2020 - Poursuites2017) %>%
  mutate(Filière = as.character(Filière)) 

diflux2 <- bind_rows(
  transmute(df,
    id = paste("2017_",Filière),
    Session = "2017",
    Cohorte = "Bacheliers 2017",
    Filière = Filière,
    Effectif = Poursuites2017
  ),
  transmute(df,
    id = paste("2017_",Filière),
    Session = "2020",
    Cohorte = "Bacheliers 2017",
    Filière = Filière,
    Effectif = min(Poursuites2017,Poursuites2020)
  ),
  transmute(df.serie,
    id = paste("2020_",Filière,Série),
    Session = "2017",
    Cohorte = paste("Bacheliers 2020",Série),
    Série,
    Filière = "Bacheliers 2020",
    Effectif = -max(Poursuites2020-Poursuites2017,0)
    ),
  transmute(df.serie,
    id = paste("2020_",Filière,Série),
    Session = "2020",
    Cohorte = paste("Bacheliers 2020",Série),
    Série,
    Filière = Filière,
    Effectif = max(Poursuites2020-Poursuites2017,0)
    )
) %>%
  mutate(Filière = factor(Filière, 
                          levels = c("Université","IUT","CPGE","STS","Autre","Bacheliers 2020"))) %>%
  mutate(Effectif = Effectif / 1000) %>%
  filter(Effectif != 0)
  
diflux2 %>%
  ggplot(aes(x=Session, y = Effectif, alluvium = id, stratum=Filière)) +
  geom_alluvium(aes(fill = Cohorte, color=Cohorte), size=0.2, width = 1/12, alpha=1) +
  geom_stratum(width = 1/6, fill = "black", color = "grey") +
  geom_text(stat = "stratum", color="white", aes(label = str_replace(after_stat(stratum)," ","\n"))) +
  scale_x_discrete(limits = c("2017", "2020"), expand = c(.1, .1)) +
  ylab("Poursuites (milliers)") +
  theme_cpesr()
```

```{r diflux4, fig.asp=2}
df.serie <- pe.pivot %>%
  filter(Session %in% c("2017","2020")) %>%
  group_by(Session, Série, Filière) %>%
  summarise(Poursuites = sum(Poursuites)) %>%
  group_by(Série, Filière) %>%
  pivot_wider(values_from = Poursuites, names_from = Session, names_prefix = "Poursuites") %>%
  mutate(diff = Poursuites2020 - Poursuites2017) %>%
  mutate(Filière = as.character(Filière)) 

diflux <- bind_rows(
  transmute(df.serie,
    id = paste("2017_",Filière,Série),
    Session = "2017",
    Cohorte = "Bacheliers 2017",
    Série,
    Filière = Filière,
    Effectif = Poursuites2017
  ),
  transmute(df.serie,
    id = paste("2017_",Filière,Série),
    Session = "2020",
    Cohorte = "Bacheliers 2017",
    Série,
    Filière = Filière,
    Effectif = min(Poursuites2017,Poursuites2020)
  ),
  transmute(df.serie,
    id = paste("2020_",Filière,Série),
    Session = "2017",
    Cohorte = "Bacheliers 2020",
    Série,
    Filière = "Bacheliers 2020",
    Effectif = -max(Poursuites2020-Poursuites2017,0)
    ),
  transmute(df.serie,
    id = paste("2020_",Filière,Série),
    Session = "2020",
    Cohorte = "Bacheliers 2020",
    Série,
    Filière = Filière,
    Effectif = max(Poursuites2020-Poursuites2017,0)
    )
) %>%
  mutate(Filière = factor(Filière, 
                          levels = c("Université","IUT","CPGE","STS","Autre","Bacheliers 2020"))) %>%
  mutate(Effectif = Effectif / 1000) %>%
  filter(Effectif != 0)
  
diflux %>%
  ggplot(aes(x=Session, y = Effectif, alluvium = id, stratum=Filière)) +
  geom_alluvium(aes(fill = Cohorte, color= Cohorte), alpha=1,width = 1/12) +
  geom_stratum(width = 1/6, fill = "black", color = "grey") +
  geom_text(stat = "stratum", color="white", aes(label = str_replace(after_stat(stratum)," ","\n"))) +
  scale_x_discrete(limits = c("2017", "2020"), expand = c(.1, .1)) +
  ylab("Poursuites (milliers)") +
  facet_wrap(Série~., scales = "free_y", ncol = 1) +
  theme_cpesr()
```
