---
title: "CPESR"
author: "CPESR"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
knitr::opts_chunk$set(fig.asp=9/16, fig.retina = 2)


library(tidyverse)
library(ggthemes)
library(ggalluvial)

library(ggcpesrthemes)
theme_cpesr_setup(authors="Julien Gossa",
                  source="SIES fr-esr-taux-poursuite-enseignement-superieur-par-academie")

theme_set(theme_cpesr())

naissances <- readxl::read_excel("../data/demo-naiss-nbre-taux.xlsx", skip = 2) %>%
  mutate(Année = as.numeric(recode(Année, "2014 y c. Mayotte"="2014"))) %>%
  filter(!is.na(Année)) %>%
  transmute(
    Session = Année + 18,
    Année.naissance = Année, 
    Naissances = `Nombre de naissances vivantes`) %>%
  arrange(Session)

pe <- read.csv2("../data/fr-esr-taux-poursuite-enseignement-superieur-par-academie.csv", dec='.') %>% 
  transmute(
    Session = Rentrée...Session,
    Bacheliers = Nombre.total.de.bacheliers,
    Poursuivants = rowSums(select(.,starts_with("Néo.bacheliers"))),
    Poursuivants.public = rowSums(select(.,
                                         contains("université"),
                                         contains("en.IUT"),
                                         contains("public"))),
    Poursuivants.université = rowSums(select(.,
                                         contains("université"),
                                         contains("en.IUT")))
  ) %>%
  summarize(across(everything(), ~ sum(.x, na.rm=TRUE)), .by = Session) 

pen <- right_join(naissances, pe) %>%
  arrange(Session)

```

## Données 

- https://data.enseignementsup-recherche.gouv.fr/explore/dataset/fr-esr-taux-poursuite-enseignement-superieur-par-academie/
- https://www.insee.fr/fr/statistiques/2381380

```{r pe.vs.n}
pen %>%
  pivot_longer(-c(Session,Année.naissance), names_to="Variable", values_to="Valeur") %>%
  mutate(Variable = relevel(factor(Variable),"Naissances")) %>%
  ggplot(aes(x=Session, y=Valeur,color=Variable,fill=Variable)) + 
  geom_line(size=1) + geom_point(shape=21, color="white",size=3,stroke=1) + 
  scale_x_continuous(labels = ~ paste(.x-18,.x,sep="\n"))+
  scale_y_continuous(labels = ~ paste(.x/1e3,"k")) 
```
```{r pe.vs.n.pred}
facteurs <- pen %>%
  mutate(across(-c(Session, Année.naissance), ~ .x/Naissances)) %>%
  tail(1) 

projections <- naissances %>%
  filter(Session > facteurs$Session) %>%
  mutate(
    Bacheliers = facteurs$Bacheliers * Naissances,
    Poursuivants = facteurs$Poursuivants * Naissances,
    Poursuivants.public = facteurs$Poursuivants.public * Naissances,
    Poursuivants.université = facteurs$Poursuivants.université * Naissances) 

predictions <- pen %>%
  bind_rows(projections) %>%
  pivot_longer(-c(Session,Année.naissance), names_to="Variable", values_to="Valeur") %>%
  mutate(Variable = relevel(factor(Variable),"Naissances")) %>%
  mutate(Type = case_when(
    Variable == "Naissances" ~ "Observations",
    Session <= facteurs$Session ~ "Observations",
    TRUE ~ "Projections")) %>%
  ggplot(aes(x=Session, y=Valeur,color=Variable,fill=Variable,linetype=Type)) + 
  geom_line(size=1) + #geom_point(shape=21,color="white",size=3,stroke=1) + 
  geom_vline(xintercept = facteurs$Session, linetype="dashed") +
  scale_x_continuous(labels = ~ paste(.x,"\n(",.x-18,")",sep=""), 
                     breaks = scales::pretty_breaks(n=10),
                     name="Session Parcoursup\n(Année de naissance)")+
  scale_y_continuous(labels = ~ paste(.x/1e3,"k"), name="Effectifs") +
  scale_alpha_manual(values=c(1,0.6)) +
  scale_shape_manual(values=c(21,24)) +
  theme(legend.position = "right")

save(predictions, file="plot-predictions.RData")

predictions
```
