---
title: "SISE"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.asp=9/16, fig.retina = 2)
library(tidyverse)
library(ggcpesrthemes)

theme_set(theme_cpesr())
theme_cpesr_setup(authors = "Julien Gossa", source="fr-esr-sise-effectifs-d-etudiants-inscrits-esr-public")
```

```{r etl, eval=FALSE}
read.sise.2019 <- function(file, rentrée.max = Inf) {
  df <- read.csv2(file, dec=".", stringsAsFactors=TRUE) %>%
    filter(RENTREE < rentrée.max) %>%
    group_by(
      Rentrée = RENTREE,
      Type.d.établissement,
      Etablissement,
      pid = Identifiant.Paysage,
      Grande.discipline,
      Secteur.disciplinaire,
      SEXE,
      DN_DE,
      Attractivité.internationale,
      LMD = factor(CURSUS_LMD, levels = c("L","M","D")),
      NIVEAU #= ifelse(DIPLOME == "LIC_PRO", "3", NIVEAU)
    ) %>%
    summarise(Etudiants = sum(Nombre.d.étudiants.inscrits..inscriptions.principales..hors.étudiants.inscrits.en.parallèle.en.CPGE,na.rm = TRUE)) %>%
    ungroup()
  return(df)
}

#df <- read.sise.2019("../data/fr-esr-sise-effectifs-d-etudiants-inscrits-esr-public.2019.csv")


read.sise <- function(file, rentrée.max = Inf) {
  read.csv2(file, dec=".", stringsAsFactors=TRUE) %>%
    filter(rentree < rentrée.max) %>%
    group_by(
      Rentrée = rentree,
      Type.d.établissement,
      Etablissement,
      pid = etablissement_id_paysage_actuel,
      Grande.discipline,
      Secteur.disciplinaire,
      SEXE,
      DN_DE,
      Attractivité.internationale,
      LMD = factor(CURSUS_LMD, levels = c("L","M","D")),
      NIVEAU #= ifelse(DIPLOME == "LIC_PRO", "3", NIVEAU)
    ) %>%
    summarise(Etudiants = sum(Nombre.d.étudiants.inscrits..inscriptions.principales..hors.étudiants.inscrits.en.parallèle.en.CPGE,na.rm = TRUE)) %>%
    ungroup()
}



sise <- read.sise("../data/fr-esr-sise-effectifs-d-etudiants-inscrits-esr-public.csv")
sise <- bind_rows(sise,
  read.sise.2019("../data/fr-esr-sise-effectifs-d-etudiants-inscrits-esr-public.2019.csv", rentrée.max = min(sise$Rentrée))
)

save(sise, file="sise.RData")
```

```{r load}
load(file="sise.RData")
```

## Tout 

```{r tout}
sise %>% 
  mutate(LMD = fct_rev(LMD)) %>%
  group_by(Rentrée, LMD) %>%
  summarise(Etudiants = sum(Etudiants)) %>%
  ggplot(aes(x=Rentrée, y= Etudiants, fill=LMD, group_by(LMD))) +
  geom_area(color="white") +
  scale_y_continuous(labels = ~ .x / 1e6, name = "Etudiants (millions)") +
  theme_cpesr_cap()
```


## Disciplines

```{r gdisc, results='asis', fig.asp=9/16}
sise %>% 
  mutate(LMD = fct_rev(LMD)) %>%
  filter(Rentrée == max(Rentrée)) %>%
  group_by(LMD, Grande.discipline) %>%
  summarise(Etudiants = sum(Etudiants)) %>%
  ggplot(aes(y=reorder(Grande.discipline,Etudiants, FUN=sum),x=Etudiants,fill=LMD)) +
  geom_col()
```

```{r disc, results='asis', fig.asp=4/3}
sise %>% 
  mutate(LMD = fct_rev(LMD)) %>%
  filter(Rentrée == max(Rentrée)) %>%
  group_by(LMD, Secteur.disciplinaire) %>%
  summarise(Etudiants = sum(Etudiants)) %>%
  ggplot(aes(y=reorder(Secteur.disciplinaire,Etudiants, FUN=sum),x=Etudiants,fill=LMD)) +
  geom_col()
```


### L3 vs M1

```{r l3m1.niveaux}
sise %>%
  group_by(Rentrée,Niveau = paste(LMD,NIVEAU, sep="-")) %>%
  summarise(Etudiants = sum(Etudiants)) %>%
  ggplot(aes(x=Rentrée, y= Etudiants, fill=Niveau)) +
  geom_area(color="white") +
  facet_wrap(Niveau~., labeller = as_labeller(label_wrap_gen(50))) +
  theme(legend.position = "None") +
  theme_cpesr_cap()
```



```{r l3m1}
sise %>%
  group_by(Rentrée,Niveau = paste(LMD,NIVEAU, sep="-")) %>%
  summarise(Etudiants = sum(Etudiants)) %>%
  filter(Niveau %in% c("L-03","M-01")) %>%
  ggplot(aes(x=Rentrée, y= Etudiants, color=Niveau)) +
  geom_line(linewidth = 1.5) + geom_point(shape = 21, stroke = 2, size = 2, fill="white") + 
  theme(legend.position = "None") +
  theme_cpesr_cap()
```

```{r l3m1.decal}
sise %>%
  group_by(Rentrée,Niveau = paste(LMD, substr(NIVEAU,2,2), sep="")) %>%
  summarise(Etudiants = sum(Etudiants)) %>%
  filter(Niveau %in% c("L3","M1")) %>%
  mutate(Rentrée = ifelse(Niveau == "L3", Rentrée+1,Rentrée)) %>%
  filter(Rentrée != 2012, Rentrée != 2022) %>%
  ggplot(aes(x=Rentrée, y= Etudiants, color=Niveau)) +
  geom_line(linewidth = 1.5) + geom_point(shape = 21, stroke = 2, size = 2, fill="white") + 
  scale_x_continuous(labels = ~ paste0("L3 ", .x-1,"\nM1 ",.x), breaks = seq(2011,2030,2), name="Cohorte") +
  scale_y_continuous(labels = ~ paste0(.x/1e3,"k"), name = "Inscriptions étudiantes") +
  ggtitle("Etudiant⋅e⋅s  inscrit⋅e⋅s en L3 à l'année N et M1 à l'année N+1" )
```

```{r l3m1.gd}
sise %>%
  filter(Grande.discipline != "Santé") %>%
  group_by(Rentrée,Niveau = paste(LMD,NIVEAU, sep="-"), Grande.discipline) %>%
  summarise(Etudiants = sum(Etudiants)) %>%
  filter(Niveau %in% c("L-03","M-01")) %>%
  ggplot(aes(x=Rentrée, y= Etudiants, color=Niveau)) +
  geom_line(linewidth = 1) + geom_point(shape = 21, stroke = 1.5, size = 1.5, fill="white") + 
  facet_wrap(Grande.discipline~., scales = "free_y") +
  theme(legend.position = "None") +
  theme_cpesr_cap()
```

```{r l3m1.gd.decal}
sise %>%
  filter(Grande.discipline != "Santé") %>%
  group_by(Rentrée,Niveau = paste(LMD, substr(NIVEAU,2,2), sep=""), Grande.discipline) %>%
  summarise(Etudiants = sum(Etudiants)) %>%
  filter(Niveau %in% c("L3","M1")) %>%
  mutate(Rentrée = ifelse(Niveau == "L3", Rentrée+1,Rentrée)) %>%
  filter(Rentrée != 2012, Rentrée != 2022) %>%
  ggplot(aes(x=Rentrée, y= Etudiants, color=Niveau)) +
  geom_line(linewidth = 1) + geom_point(shape = 21, stroke = 1.5, size = 1.5, fill="white") + 
  scale_x_continuous(labels = ~ paste0("L3 ", .x-1,"\nM1 ",.x), breaks = seq(2011,2030,2), name="Cohorte") +
  scale_y_continuous(labels = ~ paste0(.x/1e3,"k"), name = "Inscriptions étudiantes") +
  ggtitle("Etudiant⋅e⋅s  inscrit⋅e⋅s en L3 à l'année N et M1 à l'année N+1" ,  subtitle = "Par grande discipline" )+
  facet_wrap(Grande.discipline~., scales = "free_y") 
```


```{r l3m1.univ.decal, fig.width=10, fig.height=20, fig.asp=NULL}
sise %>%
  filter(Type.d.établissement %in% c("Université")) %>%
  group_by(Rentrée,Niveau = paste(LMD, substr(NIVEAU,2,2), sep=""), Etablissement) %>%
  summarise(Etudiants = sum(Etudiants, na.rm = TRUE)) %>%
  filter(Niveau %in% c("L3","M1")) %>%
  mutate(Rentrée = ifelse(Niveau == "L3", Rentrée+1,Rentrée)) %>%
  filter(Rentrée != 2012, Rentrée != 2022) %>%
  ggplot(aes(x=Rentrée, y= Etudiants, color=Niveau)) +
  geom_line() + #geom_point(shape = 21, stroke = 1.5, size = 1.5, fill="white") + 
  scale_x_continuous(labels = ~ paste0("L3 ", .x-1,"\nM1 ",.x), breaks = seq(2011,2030,2), name="Cohorte") +
  scale_y_continuous(labels = ~ paste0(.x/1e3,"k"), name = "Inscriptions étudiantes") +
  ggtitle("Etudiant⋅e⋅s  inscrit⋅e⋅s en L3 à l'année N et M1 à l'année N+1" ,  subtitle = "Par grande discipline" )+
  facet_wrap(Etablissement~., scales = "free_y", ncol = 4) 
```


## Informatique

### Effectifs

```{r info}
info <- sise %>%
  filter(Secteur.disciplinaire == "Informatique")
```


```{r info.LMD, results='asis'}
info.LMD <- info %>%
  group_by(Rentrée,LMD) %>%
  summarise(Etudiants = sum(Etudiants)) 

info.LMD %>% pivot_wider(names_from = LMD, values_from = Etudiants) %>% spoiler_table()
```

```{r info.LMD.plot}
info.LMD %>%
  mutate(LMD = fct_rev(LMD)) %>%
  ggplot(aes(x=Rentrée, y= Etudiants, fill=LMD, group_by(LMD))) +
  geom_area(color="white") +
  theme_cpesr_cap()
```

### Type d'établissement

```{r info.type, results='asis'}
info.type <- info %>%
  group_by(Rentrée,Type.d.établissement,LMD) %>%
  summarise(Etudiants = sum(Etudiants)) 

info.type %>% pivot_wider(names_from = LMD, values_from = Etudiants) %>% spoiler_table()
```

```{r info.type.plot}
info.type %>%
  mutate(LMD = fct_rev(LMD)) %>%
  ggplot(aes(x=Rentrée, y= Etudiants, fill=LMD, group_by(LMD))) +
  geom_area(color="white") +
  facet_wrap(Type.d.établissement~., scales = "free_y")+
  theme_cpesr_cap()
```


### Attractivité internationale 

```{r info.att, results='asis'}
info.att <- info %>%
  group_by(Rentrée,Attractivité.internationale,LMD) %>%
  summarise(Etudiants = sum(Etudiants)) 

info.att %>% pivot_wider(names_from = LMD, values_from = Etudiants) %>% spoiler_table()
```

```{r info.att.plot}
info.att %>%
  mutate(LMD = fct_rev(LMD)) %>%
  ggplot(aes(x=Rentrée, y= Etudiants, fill=LMD, group_by(LMD))) +
  geom_area(color="white") +
  facet_wrap(Attractivité.internationale~., scales = "free_y", labeller = as_labeller(label_wrap_gen(50))) +
  theme_cpesr_cap()
```

### Niveau

```{r info.niveau, results='asis'}
info.niveau <- info %>%
  group_by(Rentrée,Niveau = paste(LMD,NIVEAU, sep="-")) %>%
  summarise(Etudiants = sum(Etudiants)) 

info.niveau %>% pivot_wider(names_from = Niveau, values_from = Etudiants) %>% spoiler_table()
```

```{r info.niveau.plot}
info.niveau %>%
  ggplot(aes(x=Rentrée, y= Etudiants, fill=Niveau, group_by(Niveau))) +
  geom_area(color="white") +
  facet_wrap(Niveau~., labeller = as_labeller(label_wrap_gen(50))) +
  theme(legend.position = "None") +
  theme_cpesr_cap()
```


