---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(kpiESR)
library(ggcpesrthemes)

theme_set(theme_cpesr())
```

```{r load}
ens.raw <- bind_rows(
  read.csv2("../data/fr-esr-enseignants-titulaires-esr-public.csv") %>% 
    mutate(type = "permanent"),
  read.csv2("../data/fr-esr-enseignants-nonpermanents-esr-public.csv") %>% 
    mutate(
      type = "non permanent",
      Sexe = recode(Sexe,  "Féminin" = "Femme", "Masculin" = "Homme"),
      Code.groupe.CNU = as.character(Code.groupe.CNU)
    )
) %>% 
  arrange(etablissement_actuel_lib,Sexe,Rentrée)

ens.type <- ens.raw %>%
  group_by(Rentrée, type, pid = etablissement_id_paysage_actuel, Sexe, Grandes.disciplines) %>%
  summarise(effectif = sum(effectif)) %>%
  pivot_wider(names_from = Sexe, values_from = effectif) %>%
  mutate(Taux.féminité = Femme / (Femme+Homme)) %>%
  left_join(kpiESR::esr.etab) %>%
  mutate(PerimEx = case_when(
    PerimEx == "ISITE" ~ "ISITE",
    PerimEx == "IDEx" ~ "IDEx",
    TRUE ~ "NINI"
  )) 

ens <- ens.raw %>%
  group_by(Rentrée, pid = etablissement_id_paysage_actuel, Sexe, Grandes.disciplines) %>%
  summarise(effectif = sum(effectif)) %>%
  pivot_wider(names_from = Sexe, values_from = effectif) %>%
  mutate(Taux.féminité = Femme / (Femme+Homme)) %>%
  left_join(kpiESR::esr.etab) %>%
  mutate(PerimEx = case_when(
    PerimEx == "ISITE" ~ "ISITE",
    PerimEx == "IDEx" ~ "IDEx",
    TRUE ~ "NINI"
  )) 
```

## Taux de féminité des E-EC

```{r tf.gobal.ec}
ens.raw %>%
  group_by(Rentrée, Catégorie = ifelse(Code.categorie.personnels == "AM2D","AM2D","EC"), Sexe) %>%
  summarise(effectif = sum(effectif)) %>%
  pivot_wider(names_from = Sexe, values_from = effectif) %>%
  mutate(Taux.féminité = Femme / (Femme+Homme)) %>%
  arrange(Catégorie, Rentrée) %>%
  kableExtra::kable()
```


## Taux de féminité des EC

```{r tf.gobal.c}
read.csv2("../data/fr_esr_tbes_titulaires_epst.csv", dec='.') %>%
  group_by(Année, Catégorie = Catégorie.de.personnel, Sexe = sexe) %>%
  summarise(effectif = sum(Effectifs.au.31.12..en.PP.)) %>%
  pivot_wider(names_from = Sexe, values_from = effectif) %>%
  mutate(Taux.féminité = Femme / (Femme+Homme)) %>%
  arrange(Catégorie, Année) %>%
  kableExtra::kable()
```


## Taux de féminité enseignant : Permanents vs non permanents 

```{r pvsnp}
ens.type %>%
  ungroup() %>%
  filter(Rentrée == max(Rentrée)) %>%
  filter(Groupe == "Universités et assimilés") %>%
  group_by(Etablissement,type) %>%
  summarise(Homme = sum(Homme, na.rm = TRUE), Femme = sum(Femme, na.rm = TRUE)) %>%
  mutate(Taux.féminité = Femme / (Femme+Homme)) %>%
  select(-Femme,-Homme) %>%
  pivot_wider(values_from = Taux.féminité, names_from = type) %>%

  ggplot(aes(y=`non permanent`,x=permanent,label=Etablissement)) +
  geom_point() + ggrepel::geom_text_repel()
```


## IDEX, ISITE 


```{r map}
ens %>%
  filter(Rentrée == max(Rentrée)) %>%
  filter(Groupe == "Universités et assimilés") %>%
  ggplot(aes(y=PerimEx,x=Taux.féminité)) +
  geom_boxplot() +
  facet_wrap(Grandes.disciplines~.)
```


```{r evol, fig.asp=16/9}
ens %>%
  filter(Groupe == "Universités et assimilés") %>%
  filter(Grandes.disciplines %in% c("Sciences","Droit, économie et gestion","Lettres et sciences humaines","Médecine")) %>%
  group_by(pid,Grandes.disciplines) %>% 
  mutate(evol = Taux.féminité / first(Taux.féminité) * 100) %>%
  mutate(Rentrée = as.character(Rentrée)) %>%
  ggplot(aes(x=Rentrée,y=evol)) +
  geom_boxplot() +
  facet_grid(Grandes.disciplines~PerimEx)
```



```{r evol.agr}
ens %>%
  filter(Groupe == "Universités et assimilés") %>%
  filter(Grandes.disciplines %in% c("Sciences","Droit, économie et gestion","Lettres et sciences humaines","Médecine")) %>%
  group_by(Rentrée,PerimEx,Grandes.disciplines) %>% 
  summarise(Homme = sum(Homme,na.rm = TRUE), Femme=sum(Femme, na.rm = TRUE)) %>%
  mutate(Taux.féminité = Femme / (Femme+Homme)) %>%
  group_by(PerimEx,Grandes.disciplines) %>%
  mutate(evol = Taux.féminité / first(Taux.féminité) * 100) %>%
  mutate(Rentrée = as.character(Rentrée)) %>%
  ggplot(aes(x=Rentrée,y=evol, color=PerimEx, group = PerimEx)) +
  geom_line() +
  facet_grid(Grandes.disciplines~.)
```


```{r check}
ens %>%
  filter(Groupe == "Universités et assimilés", PerimEx == "ISITE") %>%
  group_by(Etablissement) %>% 
  summarise(Rentrée.min = min(Rentrée))
```


## Taux féminité vs PIA

```{r pia}
pidfix.raw <- read.csv2("fr-cpesrtmp-pidfix.csv") 
pidfix <- pidfix.raw$pid.dst
names(pidfix) <- pidfix.raw$pid.src

fin <- read.csv2("../data/fr-esr-operateurs-indicateurs-financiers.csv", na.strings="", dec=".") %>%
    group_by(pid = recode(id...paysage,!!!pidfix)) %>%
    summarise(
      ANR.hors.PIA = mean(ANR.hors.investissements.d.avenir,na.rm = TRUE),
      ANR.PIA = mean(ANR.investissements.d.avenir,na.rm = TRUE),
      SCSP = mean(Produits.de.fonctionnement.encaissables - Ressources.propres.encaissables, na.rm = TRUE),
      Budget = mean(Produits.de.fonctionnement.encaissables, na.rm = TRUE) ) 

anr <- ens %>%
  filter(Rentrée == max(Rentrée)) %>%
  filter(Groupe == "Universités et assimilés") %>%
  group_by(pid,Etablissement,Comparable,PerimEx) %>%
  summarise(Homme = sum(Homme, na.rm = TRUE), Femme = sum(Femme, na.rm = TRUE)) %>%
  mutate(Taux.féminité = Femme / (Femme+Homme)) %>%
  left_join(fin)
```



```{r anr} 
anr %>%
  filter(Comparable) %>%
  ggplot(aes(y=(ANR.hors.PIA+ANR.PIA),x=Taux.féminité, label = Etablissement, color=PerimEx)) +
  geom_point() + 
  scale_y_continuous(labels = ~ paste(.x/1e6,"M€"))
```
 
 
```{r anr.hors.pia} 
anr %>%
  filter(Comparable) %>%
  ggplot(aes(y=ANR.hors.PIA,x=Taux.féminité, label = Etablissement, color=PerimEx)) +
  geom_point() +
  scale_y_continuous(labels = ~ paste(.x/1e6,"M€"))
``` 
 
 
```{r anr.pia} 
anr %>%
  filter(Comparable) %>%
  ggplot(aes(y=ANR.PIA,x=Taux.féminité, label = Etablissement, color=PerimEx)) +
  geom_point() +
  scale_y_continuous(labels = ~ paste(.x/1e6,"M€"))
```




```{r anr.norm} 
anr %>%
  filter(Comparable) %>%
  ggplot(aes(y=(SCSP/(Homme+Femme)),x=Taux.féminité, label = Etablissement, color=PerimEx)) +
  geom_point() + 
  scale_y_continuous(labels = ~ paste(.x/1e3,"k€"))
```


```{r anr.norm2} 
anr %>%
  filter(Comparable) %>%
  pivot_longer(c(SCSP,ANR.PIA,ANR.hors.PIA), values_to = "Montant", names_to = "Ressource") %>%
  mutate(Montant.par.EEC = Montant / (Homme+Femme)) %>%
  mutate(Taux.féminité.cut = cut(Taux.féminité,c(0,0.4,0.45,0.5,1))) %>%
  ggplot(aes(y=Montant.par.EEC,x=Taux.féminité.cut, label = Etablissement, fill=Ressource)) +
  geom_boxplot() +
  facet_wrap(Ressource~.,scales = "free_y") +
  expand_limits(y=0)
```


```{r anr.line} 
anr %>%
  filter(Comparable) %>%
  pivot_longer(c(SCSP,ANR.PIA,ANR.hors.PIA), values_to = "Montant", names_to = "Ressource") %>%
  mutate(Montant.par.EEC = Montant / (Homme+Femme)) %>%
  mutate(Taux.féminité.cut = cut(Taux.féminité,c(0,0.4,0.45,0.5,1))) %>%
  ggplot(aes(y=Montant.par.EEC,x=Taux.féminité, label = Etablissement, fill=Ressource)) +
  geom_point() + geom_smooth(method="lm") +
  facet_wrap(Ressource~.,scales = "free_y") +
  expand_limits(y=0)
```