---
title: "Indicateurs financiers d'établissement"
output: github_document
---
  
```{r setup.etab, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# `r etab`

```{r data}
#etab <- "Université de Strasbourg"

fin.etab <- fin.pivot %>% filter(etablissement == etab)
grp <- fin.etab$groupe[[1]]
fin.all <- bind_rows(
  fin.etab,
  fin.pivot.groupe %>% filter(groupe==grp, Aggrégation=="Moyenne"),
  fin.pivot.total %>% filter(Aggrégation=="Moyenne")
) %>%
  mutate(
    etablissement = factor(etablissement, 
                           levels = c("Global","Groupe",etab),
                           labels = c("Moyenne globale MESRI",paste("Moyenne du groupe",grp),etab))
  )
```


## Focus Résultat et Solde

```{r etab.focus, fig.width=8, fig.height=4.5}
fin.all  %>%
  filter(Indicateur %in% c("Résultat.net.comptable","Solde.budgétaire","Acquisitions.d.immobilisations")) %>%
  mutate(Valeur = Valeur / 10^6) %>%
  ggplot(aes(x=exercice,y=Valeur,color=etablissement)) +
    geom_point(size=2) + geom_line(aes(group=etablissement)) +
    scale_color_brewer(palette="Purples", name="") +
    facet_wrap(Indicateur~., scales="free", ncol=1) +
    ggtitle(paste0("Indicateurs financiers de ",etab)) + 
    theme_cpesr() 
    #theme(legend.direction="vertical", legend.position = "right")
```

## Focus Masse salariale


```{r etab.focus.ms.et.pfe, fig.width=8, fig.height=4.5}
fin.all  %>%
  filter(Indicateur %in% c("Produits.de.fonctionnement.encaissables","Dépenses.de.personnel")) %>%
  group_by(Indicateur,etablissement) %>%
  mutate(Evolution = Valeur / first(Valeur) * 100) %>%
  ggplot(aes(x=exercice,y=Evolution,color=Indicateur, linetype=etablissement)) +
    geom_point(size=2) + geom_line(aes(group=paste(Indicateur,etablissement))) +
    #scale_color_brewer(palette="Purples", name="") +
    #facet_wrap(Indicateur~., scales="free", ncol=1) +
    ggtitle(paste0("PFE et Dépenses de personnel de ",etab)) + 
    theme_cpesr() 
    #theme(legend.direction="vertical", legend.position = "right")
```


```{r etab.focus.ms.vs.pfe, fig.width=8, fig.height=4.5}
fin %>%
  filter(etablissement == etab) %>%
  group_by(exercice) %>%
  summarize(
    MS.sur.PFE = mean(Dépenses.de.personnel...Produits.encaissables, na.rm=TRUE),
  ) %>%
  ggplot(aes(x=exercice, y=MS.sur.PFE)) +
    geom_line(aes(color=MS.sur.PFE,group="Indicateur"), size=1) +
    geom_point(shape=21, color="white", size=4, stroke = 1, aes(fill=MS.sur.PFE)) + 
    #expand_limits(y=0) +
    ylab("") +
    scale_y_continuous(labels = ~ scales::percent(.x, scale=1)) + #, limits = c(75,85)) +
    scale_fill_distiller(palette="Greens", direction = 0, limits = c(0,100), guide = "none") +
    scale_color_distiller(palette="Greens", direction = 0, limits = c(0,100), guide = "none") +
    ggtitle(paste0("Part des dépenses de personnels dans les produits encaissables"), subtitle=etab) +
    theme_cpesr_cap()
```


## Tous les indicateurs

```{r etab, fig.width=10, fig.height=30}
fin.all %>% 
  ggplot(aes(x=exercice,y=Valeur,color=etablissement)) +
  geom_point(size=2) + geom_line(aes(group=etablissement)) +
  scale_color_brewer(palette="Purples") +
  facet_wrap(Indicateur~., scales="free", ncol=2) +
  theme_cpesr() +
  theme(legend.direction="vertical")
```
