---
title: "Bugdet"
author: "CPESR"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(dplyr.summarise.inform = FALSE)
knitr::opts_chunk$set(fig.asp = 9/16, fig.retina = 2)

library(tidyverse)
library(ggcpesrthemes)
theme_set(theme_cpesr())
theme_cpesr_setup(authors = "Julien Gossa", source = "https://github.com/cpesr/RFC/")
```

## Données 

- url source

```{r load}
budget <- read.csv2("data/budget.csv") %>%
  left_join(
    kpiESR::esr %>%
      filter(Etablissement == "Ensemble") %>%
      filter(Rentrée > 2012) %>%
      transmute(
        Année = Rentrée + 1,
        `Établissements MESR` = kpi.FIN.P.ressources / 1e9
      )
  ) %>%
  mutate(`P150 (moins CASPension)` = P150 - CASPension) %>%
  pivot_longer(-c(Année,déflateur), names_to = "Dépense", values_to = "Valeur") %>%
  mutate(Valeur2025 = Valeur / déflateur)
```

## Explorations

```{r}
budget %>% 
  ggplot(aes(x=Année,y=Valeur2025,color=Dépense)) + 
  geom_vline(xintercept = c(2007,2018,2019)) +
  geom_line(size=1) +
  scale_x_continuous(breaks = seq(2003,2030, by=2), name=NULL) +
  scale_y_continuous(labels = ~ paste(.x,"Md€"), name=NULL) +
  annotate("text",label="Réforme du CIR", x=2007, y=30, vjust = -0.5, hjust = 1, angle=90) +
  annotate("text",label="Réforme de l'alternance", x=2018, y=30, vjust = -0.5, hjust = 1, angle=90) +
  annotate("text",label="Loi Recherche", x=2020, y=30, vjust = -0.5, hjust = 1, angle=90) 
  
```

```{r}
library(ggrepel)

depense_plot <- function(vars) {
  reformes <- budget %>% 
    filter(Dépense == "CIR" & Année == 2006 | Dépense == "Alternance" & Année == 2018 | Dépense == vars[3] & Année == 2020 ) %>%
    add_column(reforme = c("Réforme du CIR", "Réforme de l'alternance", "Loi Recherche"))
  
  budget %>% 
    filter(Dépense %in% vars) %>%
    ggplot(aes(x=Année,y=Valeur2025)) + 
    geom_segment(data=reformes,aes(xend=Année,yend=32), color = "grey") +
    geom_text(data=reformes,aes(y=35, label=reforme),vjust = -0.5, hjust = 1, angle=90) +
    geom_line(aes(color=Dépense), size=1) +
    geom_point(data=reformes,aes(color=Dépense), shape=21, size=2, stroke=1.5, fill="white") +
    scale_x_continuous(breaks = seq(2003,2030, by=2), name=NULL) +
    scale_y_continuous(labels = ~ paste(.x,"Md€"), name=NULL) +
    labs(
      title = "Dépenses nationales et grandes réformes",
      y = "Md€ (2020)"
    )
}

depense_plot(c("CIR","Alternance","Établissements MESR"))
depense_plot(c("CIR","Alternance","P150"))
depense_plot(c("CIR","Alternance","P150 (moins CASPension)"))
```


```{r}
e <- new.env()

load("RD.RData", envir = e)

e$budget <- budget
e$depense_plot <- depense_plot

save(list = ls(e), envir = e, file = "RD.RData")
```




