---
title: "CPESR"
author: "CPESR"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(dplyr.summarise.inform = FALSE)
knitr::opts_chunk$set(fig.asp = 9/16, fig.retina = 2)

library(tidyverse)
library(ggcpesrthemes)
theme_set(theme_cpesr())
theme_cpesr_setup(authors = "Julien Gossa", source = "https://github.com/cpesr/RFC/")
```

## Données 

```{r load}
rdfrge <- read.csv("RD-fr-ge.csv", dec='.')
rdevol <- read.csv("RD-evolution.csv", dec='.')
```

## Explorations

```{r}
rdfrge %>%
  pivot_longer(-Année, values_to = "RDpPIB", names_to = "Pays") %>%
  ggplot(aes(x=Année,y=RDpPIB,color=Pays)) + geom_line(size=1) + geom_point(size=2,shape=21,stroke=1.5, fill="white") +
  scale_y_continuous(labels = ~ paste(.x,"%")) +
  scale_color_brewer(palette="Dark2") +
  labs(
    title = "Dépense nationale de R&D en pourcentage de PIB",
    subtitle = "France et Allemagne, entre 1996 et 2023",
    y = "RD (% PIB)"
  )
```


```{r}
rdfrge %>%
  pivot_longer(-Année, values_to = "RDpPIB", names_to = "Pays") %>%
  ggplot(aes(x=Année,y=RDpPIB,color=Pays)) + geom_smooth(method="lm", se=FALSE) +
  geom_point(size=2) +
  scale_y_continuous(labels = ~ paste(.x,"%")) +
  scale_color_brewer(palette="Dark2") +
  labs(
    title = "Dépense nationale de R&D en pourcentage de PIB",
    subtitle = "France et Allemagne, entre 1996 et 2023",
    y = "RD (% PIB)"
  )
```



```{r}
rdevol %>%
  ggplot(aes(x=RD_evol.1996_2023,y=reorder(Pays,RD_evol.1996_2023), color=(RD_evol.1996_2023>0))) + 
  
  annotate(
    "rect",
    xmin = -Inf,
    xmax = Inf,
    ymin = which(order(rdevol$RD_evol.1996_2023) == which(rdevol$Pays == "France")) + 1.5,
    ymax = which(order(rdevol$RD_evol.1996_2023) == which(rdevol$Pays == "France")) + 0.5,
    fill = "grey90"
  ) +
  geom_segment(xend=0, size=1) +
  geom_point(size=2) +
  scale_x_continuous(labels = ~ sprintf("%+1.1f", .x), breaks = seq(-1,2,0.5)) +
  labs(
    title = "Evolution de la dépense nationale de R&D en pourcentage de PIB",
    subtitle = "Entre 1996 et 2023",
    x = "Différence 1996-2023 (en points de % PIB)",
    y = NULL
  ) +
  theme(legend.position = "None")
```




## Corporation

```{r}
rdcorp <- read.csv("scrapper/rd-expenses-annual.csv")

rdcorp %>%
  filter(annual_year == 2025) %>%
  arrange(desc(annual_billion)) %>%
  head(10) %>%
  add_row(ticker="FRA", company_name="MIRES", country="France", annual_year=2025, annual_billion=35.21) %>%
  arrange(desc(annual_billion)) %>%
  mutate(country = factor(country, levels = unique(country))) %>%
  head(11) %>%
  ggplot(aes(x=annual_billion,y=reorder(company_name,annual_billion),fill=country)) +
  geom_col() +
  geom_text(aes(label = paste(round(annual_billion), "Md$")), hjust = 0, nudge_x = 0.5) +
  scale_fill_brewer(palette = "Set2", direction=-1) +
  expand_limits(x=120) +
  coord_cartesian(clip = "off") +
  labs(
    title = "Dépenses R&D d'entreprises vs. MIRES",
    x = "Dépense (Md$)",
    y = NULL, 
    fill = "Pays") +
  theme(legend.position = "inside", legend.position.inside = c(0.85, 0.3))
```


```{r}
top <- rdcorp %>%
  filter(annual_year == 2025) %>%
  arrange(desc(annual_billion)) %>%
  head(5) %>%
  pull(ticker)


dirda <- read.csv2("insee/dirda.csv")

rd <- rdcorp %>%
  filter(ticker %in% top) %>%
  bind_rows(
    dirda %>%
      transmute(
        ticker = "DIRDA",
        company_name = "DIRDA",
        country = "France",
        annual_year = Année,
        annual_billion = DIRDA * 1.15
      ) %>%
      filter(annual_year>2010) %>%
      add_row(annual_year = 2024) %>%
      add_row(annual_year = 2025) %>%
      fill(everything(), .direction = "down")      
  )

labels <- rd %>%
  arrange(annual_year) %>%
  group_by(ticker) %>%
  slice_tail(n=1)

rd %>%
  ggplot(aes(x=annual_year, y=annual_billion, color=country, group=ticker)) + 
  geom_line(size = 1) +
  ggrepel::geom_text_repel(data=labels, aes(label=company_name), color="black", direction="y", nudge_x = 0.2, hjust=0) +
  expand_limits(x=2027.5) +
  scale_color_brewer(palette="Set1") +
  labs(
    title = "Dépenses R&D des GAFAMS et des administrations françaises",
    subtitle = "DIRDA = dépense intérieure de R&D des administrations françaises",
    x = "Année",
    y = "Dépense de R&D (Md$)",
    color = NULL
  ) +
  theme(legend.position = "None")
```
