---
title: "CPESR"
author: "CPESR"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(dplyr.summarise.inform = FALSE)
knitr::opts_chunk$set(fig.asp = 9/16, fig.retina = 2)

library(tidyverse)
library(ggcpesrthemes)
theme_set(theme_cpesr())
theme_cpesr_setup(authors = "Julien Gossa", source = "Base SIRENE https://github.com/cpesr/RFC/Siren")
```

## Données 

- https://www.data.gouv.fr/fr/datasets/base-sirene-des-entreprises-et-de-leurs-etablissements-siren-siret/
- https://insee.fr/fr/information/2406147
- https://www.insee.fr/fr/information/2028129
- https://www.data.gouv.fr/fr/datasets/repertoire-national-des-certifications-professionnelles-et-repertoire-specifique/

```{r load, eval=FALSE}
naf <- read.csv2("Activité.csv", stringsAsFactors = TRUE)

cj <- left_join(
  readxl::read_xls("cj_septembre_2022.xls", sheet = 3, skip = 3) %>%
    mutate(subcode = str_sub(Code,1,1)) %>%
    rename(categorieJuridiqueDetaillee=Libellé),
  readxl::read_xls("cj_septembre_2022.xls", sheet = 1, skip = 3) %>%
    rename(subcode = Code,
           categorieJuridique=Libellé)) %>%
  mutate(categorieJuridiqueGroupee = fct_other(categorieJuridique,
    keep=c("Entrepreneur individuel","Personne morale de droit public soumise au droit commercial","Personne morale et organisme soumis au droit administratif","Personne morale de droit étranger"),
    other_level = "Autres"
  )) %>%
  mutate(categorieJuridiqueSecteur = fct_collapse(categorieJuridiqueGroupee,
    Public=c("Personne morale de droit public soumise au droit commercial","Personne morale et organisme soumis au droit administratif"),
    other_level = "Privé"
  )) %>%
  select(-subcode)

cpesr.siren <- read.csv2("fr-cpesr-siren.csv") %>%
  slice_head(n=1,by=siren) %>%
  select(siren,Etablissement,Secteur) %>%
  filter(Secteur != "privé")

tranches <- read.csv("TranchesEffectif.csv", colClasses = "character", stringsAsFactors = TRUE) %>%
  mutate(TrancheEffectif = factor(TrancheEffectif,levels=TrancheEffectif))

rncp <- full_join(
  read.csv2("export_fiches_CSV_Certificateurs_2024_02_18.csv", colClasses = "character") %>%
    transmute(
      Numero_Fiche,
      siret = str_sub(Siret_Certificateur,2),
      NomRNCP = Nom_Certificateur,
      Type = "CertificationsRNCP"
    ),
  read.csv2("export_fiches_CSV_Partenaires_2024_02_18.csv", colClasses = "character") %>%
    transmute(
      Numero_Fiche,
      siret = str_sub(Siret_Partenaire,2),
      NomRNCP = Nom_Partenaire,
      Type = "PartenariatsRNCP"
    )
) %>% filter(siret != "")

rncp.siret <- rncp %>%
  summarise(Nombre = n_distinct(Numero_Fiche), .by = c(siret,NomRNCP,Type)) %>%
  pivot_wider(names_from = Type, values_from = Nombre, values_fill = 0)

rncp.siren <- rncp %>%
  mutate(siren = str_sub(siret,1,9)) %>%
  mutate(NomRNCP = paste(unique(NomRNCP), collapse = ";"), .by = siren) %>%
  summarise(Nombre = n_distinct(Numero_Fiche), .by = c(siren,NomRNCP,Type)) %>%
  pivot_wider(names_from = Type, values_from = Nombre, values_fill = 0)
  

sirene <- read.csv("StockUniteLegale_utf8_ens.csv", colClasses = "character", na.strings = c("","[ND]")) %>%
  select(siren, dateCreationUniteLegale, 
        sigleUniteLegale, nomUniteLegale, nomUsageUniteLegale, denominationUniteLegale,
        trancheEffectifsUniteLegale, categorieEntreprise, categorieJuridiqueUniteLegale,
        etatAdministratifUniteLegale, dateDebut,
        activitePrincipaleUniteLegale, nomenclatureActivitePrincipaleUniteLegale,
        caractereEmployeurUniteLegale) 
  
sirene_formateur <- function(.x) {
  .x %>%
  # Fixes
  mutate(caractereEmployeurUniteLegale = (caractereEmployeurUniteLegale == "O")) %>%
  mutate(trancheEffectifsUniteLegale = ifelse(
    is.na(trancheEffectifsUniteLegale) & caractereEmployeurUniteLegale == FALSE,
    "NN",trancheEffectifsUniteLegale)) %>%
  mutate(categorieEntreprise = ifelse(
    is.na(categorieEntreprise) & caractereEmployeurUniteLegale == FALSE,
    "PME",categorieEntreprise)) %>%
  # Formalisation
  mutate(across(c(trancheEffectifsUniteLegale, categorieEntreprise, categorieJuridiqueUniteLegale, activitePrincipaleUniteLegale, nomenclatureActivitePrincipaleUniteLegale,etatAdministratifUniteLegale), as.factor)) %>%
  mutate(categorieEntreprise = factor(categorieEntreprise, 
                                      levels = c("PME","ETI","GE")) ) %>%
  left_join(tranches, by = join_by(trancheEffectifsUniteLegale == Code)) %>%
  left_join(cj, by = join_by(categorieJuridiqueUniteLegale == Code)) %>%
  left_join(rncp.siren) %>%
  left_join(cpesr.siren %>% select(siren,NomMESR=Etablissement)) %>%
  mutate(Categorie = case_when(
    !is.na(NomMESR) ~ "Public MESR",
    categorieJuridiqueSecteur == "Public" ~ "Public hors MESR",
    !is.na(NomRNCP) ~ "Privé avec RNCP",
    trancheEffectifsUniteLegale %in% c("NN","00","01") ~ "Privé individuel",
    categorieJuridiqueGroupee == "Personne morale de droit étranger" ~ "Privé droit étranger",
    TRUE ~ "Privé autre"
  )) %>%
  mutate(Categorie = factor(Categorie, levels=c("Public MESR","Public hors MESR", "Privé avec RNCP", "Privé individuel", "Privé droit étranger", "Privé autre"))) %>%
  left_join(naf, by = join_by(
    nomenclatureActivitePrincipaleUniteLegale == nomenclatureActivitePrincipale,
    activitePrincipaleUniteLegale == activitePrincipale))
}

sirene <- sirene_formateur(sirene) %>%
  filter(!is.na(Activité)) 

save(sirene, file="sirene.Rdata")
```

```{r load.full, eval=FALSE}
sirene.full <- read.csv("StockUniteLegale_utf8_shrink.csv", colClasses = "character", na.strings = c("","[ND]")) %>%
  filter(etatAdministratifUniteLegale == "A") %>%
  summarise(Nombre = n(),
            .by = c(trancheEffectifsUniteLegale,etatAdministratifUniteLegale,categorieEntreprise,categorieJuridiqueUniteLegale,activitePrincipaleUniteLegale,nomenclatureActivitePrincipaleUniteLegale,caractereEmployeurUniteLegale)) %>%
  mutate(siren = as.character(row_number())) %>%
sirene_formateur()
  
save(sirene.full,file="sirene_full.Rdata")
```



```{bakup}
# sirene_hist <- read.csv("StockEtablissementHistorique_utf8_ens.csv", colClasses = "character", na.strings = c("","[ND]")) %>%
#   mutate(across(starts_with("changement"), ~ (str_to_lower(.x)=="true"))) %>%
#   mutate(caractereEmployeurEtablissement = (caractereEmployeurEtablissement=="O")) %>%
#   left_join(naf) %>%
#   filter(!is.na(Activité)) 
# 
# 
# siret <- sirene %>% 
#   group_by(siren,siret,Activité) %>%
#   arrange(dateDebut) %>%
#   summarise(
#     dateDebut = first(dateDebut),
#     across(c(dateFin,etatAdministratifEtablissement,enseigne1Etablissement,denominationUsuelleEtablissement,nomenclatureActivitePrincipaleEtablissement), last),
#     changementActivitePrincipaleEtablissement = first(changementActivitePrincipaleEtablissement),
#     caractereEmployeurEtablissement = sum(caractereEmployeurEtablissement,na.rm=TRUE)
#   ) %>%
#   mutate(caractereEmployeurEtablissement = (caractereEmployeurEtablissement>0)) %>%
#   ungroup() %>%
#   left_join(cpesr.siren %>% select(siren,NomMESR=Etablissement)) %>%
#   left_join(rncp.siret)
# 
# 
# siren <- siret %>%
#   group_by(siren) %>%
#   summarise(
#     dateDebut = min(dateDebut),
#     dateFin = max(dateFin),
#     nombreEtablissements = n(),
#     nombreEtablissementsActifs = sum(etatAdministratifEtablissement == "A",na.rm = TRUE),
#     nombreEtablissementsEmployeurs = sum(caractereEmployeurEtablissement,na.rm=TRUE),
#     enseigne1Etablissement = paste(unique(enseigne1Etablissement), collapse = ";"),
#     denominationUsuelleEtablissement = paste(unique(denominationUsuelleEtablissement), collapse = ";")
#   ) %>%
#   mutate(
#     etatAdministratifEtablissement = ifelse(nombreEtablissementsActifs>0,"A","F"),
#     caractereEmployeurEtablissement = (nombreEtablissementsEmployeurs>0) ) %>%
#   left_join(siret %>%
#     summarise(nb=n(), .by = c(siren,Activité)) %>%
#     group_by(siren) %>%
#     arrange(desc(nb)) %>%
#     summarise(
#       Activité = first(Activité),
#       AutresActivité = paste(unique(Activité), collapse = ";")) %>%
#     ungroup()) %>%
#   left_join(cpesr.siren %>% select(siren,NomMESR=Etablissement)) %>%
#   left_join(rncp.siren)
```




```{r load.save}
load("sirene.Rdata")
load("sirene_full.Rdata")
activité.sup = c("Formation continue d'adultes","Enseignement supérieur","Enseignement de disciplines sportives et d'activités de loisirs","Autres enseignements")
```


## Catégories

Attention : échelle logarithmique.

```{r categorie, fig.asp=4/3}
plot_categories <- function(.x) {
  .x %>%
  filter(etatAdministratifUniteLegale == "A") %>%
  summarise(NombreOrganismes = n(), .by=c(Activité,categorie)) %>% 
  ggplot(aes(x=categorie, y=NombreOrganismes,fill=categorie)) + 
    geom_col() +
    scale_y_log10() +
    #scale_x_discrete(limits=rev) +
    facet_wrap(Activité~., labeller = labeller(Activité = label_wrap_gen(25))) +
  theme(axis.text.x=element_blank())
}
```


### Tranche effectif

```{r categorie.tranche, fig.asp=3/4}
sirene %>%
  mutate(categorie = TrancheEffectif) %>%
  plot_categories()
```


### Categorie d'entreprise

```{r categorie.ce, fig.asp=3/4}
sirene %>%
  mutate(categorie = categorieEntreprise) %>%
  plot_categories()
```

### Categorie juridique

```{r categorie.cj, fig.asp=3/4}
sirene %>%
  mutate(categorie = categorieJuridique) %>%
  plot_categories()
```

```{r categorie.cjg, fig.asp=3/4}
sirene %>%
  mutate(categorie = categorieJuridiqueGroupee) %>%
  plot_categories()
```


### RNCP

```{r categorie.rncp, fig.asp=3/4}
sirene %>%
  mutate(categorie = case_when(
    CertificationsRNCP > 0 & PartenariatsRNCP > 0 ~ "Cert+Part",
    CertificationsRNCP == 0 & PartenariatsRNCP > 0 ~ "Partenaires",
    CertificationsRNCP > 0 & PartenariatsRNCP == 0 ~ "Certifictateur",
    TRUE ~ " Hors RNCP"
  )) %>%
  plot_categories()
```

#### Nombre certifications+partenariats

```{r categorie.rncp2, fig.asp=3/4}
sirene %>%
  filter(!is.na(NomRNCP)) %>%
  mutate(categorie = cut(CertificationsRNCP + PartenariatsRNCP, breaks = c(0,1,2,5,10,50,100,300,Inf), right = TRUE)) %>%
  plot_categories()
```

### Secteur

```{r categorie.secteur, fig.asp=3/4}
sirene %>%
  mutate(categorie = categorieJuridiqueSecteur) %>%
  plot_categories()
```

### MESR

```{r categorie.mesr, fig.asp=3/4}
sirene %>%
  mutate(categorie = ifelse(is.na(NomMESR),"Hors MESR","MESR")) %>%
  plot_categories()
```


```{r categorie.mesr2, fig.asp=3/4}
sirene %>%
  mutate(categorie = case_when(
    !is.na(NomMESR) ~ "MESR",
    TRUE ~ categorieJuridiqueSecteur) ) %>%
  plot_categories()
```

```{r mesr.prive, results='asis'} 
sirene %>% 
  filter(!is.na(NomMESR)) %>%
  filter(categorieJuridiqueSecteur == "Privé") %>%
  select(NomMESR, categorieJuridique,categorieJuridiqueGroupee,categorieJuridiqueSecteur) %>% spoiler_table("MESR privé", trim = Inf)
```

### All

```{r categorie.all, fig.asp=3/4}
sirene %>%
  mutate(categorie = Categorie) %>%
  plot_categories()
```


```{r cat.all.txt, results='asis'}
sirene %>%
  filter(etatAdministratifUniteLegale == "A") %>%
  group_by(
    Categorie,
    Activité,
    categorieEntreprise,
    categorieJuridiqueSecteur,
    categorieJuridiqueGroupee,
    MESR = !is.na(NomMESR),
    RNCP = !is.na(NomRNCP)
  ) %>%
  summarise(Nombre = n()) %>%
  spoiler_table("Toutes catégories")
```

## Evolutions

```{r functions}
open_close <- function(.x, fs="fixed") {
  bind_rows(
    .x %>% mutate(Date = dateCreationUniteLegale, Type="Création"),
    .x %>% filter(etatAdministratifUniteLegale == "C") %>%
      mutate(Date = dateDebut, Type="Cessation")) %>% 
    arrange(Date) %>% 
    mutate(Année = as.numeric(str_sub(Date,1,4))) %>%
    summarise(Nombre = n(), .by = c(Indicateur, Année, Type)) %>%
    filter(!is.na(Année), Année < 2024, Année > 1970) %>%
    ggplot(aes(x=Année,y=Nombre,color=Type)) + 
    geom_line(size=0.5) + # geom_point(shape=21,stroke=2,size=2,fill="white") +
    scale_x_continuous(breaks = scales::pretty_breaks()) +
    facet_wrap(Indicateur~., labeller = labeller(Indicateur = label_wrap_gen(25)), scales = fs) +
    ggtitle("Ouverture et fermeture de sociétés dans l'activité Enseignement") +
    cpesr_cap()
}
```



# Ouvertures / Fermetures

```{r, fig.asp=3/4}
open_close(sirene %>% mutate(Indicateur=Activité))
```

```{r, fig.asp=3/4}
open_close(sirene %>% 
             filter(Activité=="Enseignement supérieur") %>% 
             mutate(Indicateur=Categorie), 
           fs = "free_y")
```

# Nombre d'établissements

```{r, fig.asp=3/4}
nombre_ouverts_data <- function(.x) {
  bind_rows(
    .x %>% mutate(Date = dateCreationUniteLegale, Type="Création"),
    .x %>% filter(etatAdministratifUniteLegale == "C") %>%
      mutate(Date = dateDebut, Type="Cessation")) %>% 
    arrange(Date) %>%
    mutate(Année = as.numeric(str_sub(Date,1,4))) %>%
    mutate(Nombre = cumsum(ifelse(Type=="Création",1,-1)), .by=c(Activité,Indicateur)) %>% 
    filter(Année < 2024, Année > 1985) %>%
    slice_tail(n=1, by = c(Activité,Année,Indicateur)) %>%
    select(Activité,Année,Indicateur,Nombre)
}

nombre_ouverts_plot <- function(.x, position="stack") {
  
  poslab <- ~ paste(.x/1e3,"k")
  if(position=="fill") poslab <- scales::percent
  
  .x %>%
    ggplot(aes(x=Année,y=Nombre,fill=Indicateur,color=Indicateur)) + 
    geom_area(position=position) + # geom_point(shape=21,stroke=2,size=2,fill="white") +
    scale_y_continuous(labels=poslab, name = "Nombre de SIREN (milliers)") +
    facet_wrap(Activité~., labeller = labeller(Activité = label_wrap_gen(25))) +
    scale_color_brewer(palette = "Paired", limits=levels(.x$Indicateur)) +
    scale_fill_brewer(palette = "Paired", limits=levels(.x$Indicateur)) +
    ggtitle("Nombre d'établissements dans l'activité Enseignement") +
    theme(legend.title = element_blank()) +
    cpesr_cap()
}

nombre_ouverts_zooms <- function(.x, position="stack") {
  no <- nombre_ouverts_data(.x)
  
  print(no %>% 
    nombre_ouverts_plot(position))
  
  print(no %>% 
    filter(Activité %in% activité.sup) %>%
    nombre_ouverts_plot(position) +
    geom_vline(xintercept = 2008))
  
  print(no %>% 
    filter(Activité == "Enseignement supérieur") %>%
    nombre_ouverts_plot(position) +
    geom_vline(xintercept = 2008))
}
```


```{r nombre, fig.asp=3/4}
sirene %>% 
  mutate(Indicateur = Categorie) %>%
  nombre_ouverts_zooms()
```


```{r nombre.fill, fig.asp=3/4}
sirene %>% 
  mutate(Indicateur = Categorie) %>%
  nombre_ouverts_zooms("fill")
```


```{r nombre.horsindiv, fig.asp=3/4}
sirene %>% 
  filter(Categorie != "Privé individuel") %>%
  mutate(Indicateur = Categorie) %>%
  nombre_ouverts_zooms()
```

```{r nombre.horsindiv.fill, fig.asp=3/4}
sirene %>% 
  filter(Categorie != "Privé individuel") %>%
  mutate(Indicateur = Categorie) %>%
  nombre_ouverts_zooms(position="fill")
```

```{r nombres.raw, results='asis'}
sirene %>% 
  filter(Activité == "Enseignement supérieur") %>%
  mutate(Indicateur = Categorie) %>%
  nombre_ouverts_data() %>%
  filter(Année %in% c(range(Année),2008)) %>%
  mutate(Part = scales::percent(Nombre / sum(Nombre), accuracy=1), .by=c(Année,Activité)) %>%
  pivot_wider(values_from = c(Nombre,Part), names_from = Année) %>%
  mutate(Evolution=Nombre_2023 / Nombre_1986) %>%
  spoiler_table("Enseignement supérieur", trim = Inf)
```

```{r nombres.raw.horsindiv, results='asis'}
sirene %>% 
  filter(Categorie != "Privé individuel") %>%
  filter(Activité == "Enseignement supérieur") %>%
  mutate(Indicateur = Categorie) %>%
  nombre_ouverts_data() %>%
  filter(Année %in% range(Année)) %>%
  mutate(Part = scales::percent(Nombre / sum(Nombre), accuracy=1), .by=c(Année,Activité)) %>%
  pivot_wider(values_from = c(Nombre,Part), names_from = Année) %>%
  mutate(Evolution=Nombre_2023 / Nombre_1986) %>%
  spoiler_table("Enseignement supérieur hors indiv", trim = Inf)
```


```{r nombres.raw.tot, results='asis'}
sirene %>% 
  #filter(Categorie != "Privé individuel") %>%
  filter(Activité == "Enseignement supérieur") %>%
  mutate(Indicateur = Categorie) %>%
  nombre_ouverts_data() %>%
  filter(Année %in% range(Année)) %>%
  summarize(Nombre = sum(Nombre), .by=c(Année)) %>%
  spoiler_table("Enseignement supérieur total", trim = Inf)
```

## Listes

```{r etr, results='asis'}
sirene %>%
  filter(Categorie == "Privé droit étranger") %>%
  spoiler_table("Privé droit étranger", trim = Inf)
```


## Comparaisons

```{r cmp.categorie}
bind_rows(sirene %>% mutate(Activité="Enseignement",Nombre=1), 
          sirene.full %>% mutate(Activité="Toutes")) %>%
  summarise(Nombre = sum(Nombre), .by=c(Activité,categorieJuridique)) %>%
  mutate(Part = Nombre/sum(Nombre), .by=Activité) %>%
  filter(!is.na(categorieJuridique)) %>%
  ggplot(aes(y=reorder(categorieJuridique,Part),x=Part,fill=Activité)) +
  geom_col(position = "dodge") +
  scale_x_continuous(labels=scales::percent) +
  theme(axis.title.y = element_blank(), plot.title = element_text(hjust=1)) +
  ggtitle("Part des statuts d'entreprise dans chaque groupe d'activité") +
  cpesr_cap()
```


```{r cmp.categorie.1}
bind_rows(sirene %>% mutate(Activité="Enseignement",Nombre=1), 
          sirene %>% filter(Activité=="Enseignement supérieur") %>% mutate(Nombre=1),
          sirene.full %>% mutate(Activité="Toute")) %>%
  mutate(Activité = factor(Activité, levels = c("Toute","Enseignement","Enseignement supérieur"))) %>%
  mutate(categorieJuridique = fct_lump(categorieJuridique, 3, other_level = "Autres")) %>%
  summarise(Nombre = sum(Nombre), .by=c(Activité,categorieJuridique)) %>%
  mutate(Part = Nombre/sum(Nombre), .by=Activité) %>%
  filter(!is.na(categorieJuridique)) %>%
  ggplot(aes(y=reorder(categorieJuridique,Part),x=Part,fill=Activité)) +
  geom_col(position = "dodge") +
  scale_x_continuous(labels=scales::percent) +
  scale_fill_brewer(palette = "Set1", direction = 1) +
  theme(axis.title.y = element_blank(), plot.title = element_text(hjust=1), legend.justification = c(1,0)) +
  ggtitle("Part des statuts juridiques dans selon l'activité") +
  cpesr_cap()
```

```{r cmp.categorie.2}
sirene.full %>%
  mutate(Activité = ifelse(is.na(Activité),"Autre","Enseignement")) %>%
  summarise(Nombre = sum(Nombre), .by=c(Activité,categorieJuridique)) %>%
  mutate(Part = Nombre/sum(Nombre), .by=c(categorieJuridique)) %>%
  filter(!is.na(categorieJuridique)) %>%
  ggplot(aes(y=reorder(categorieJuridique,Part),x=Part,fill=Activité)) +
  geom_col(position = "dodge") +
  scale_x_continuous(labels=scales::percent) +
  theme(axis.title.y = element_blank(), plot.title = element_text(hjust=1)) +
  ggtitle("Par ") +
  cpesr_cap()
```

```{r cmp.categorie.3, results='asis'}
df <- bind_rows(
  sirene.full %>%
    mutate(Activité = ifelse(is.na(Activité),"Autre","Enseignement")) %>%
    summarise(Nombre = sum(Nombre), .by=c(Activité,categorieJuridique)) %>%
    mutate(Part = Nombre/sum(Nombre), .by=categorieJuridique) %>%
    filter(!is.na(categorieJuridique)),
  sirene.full %>%
    mutate(Activité = ifelse(is.na(Activité),"Autre","Enseignement")) %>%
    summarise(Nombre = sum(Nombre), .by=c(Activité)) %>%
    mutate(Part = Nombre/sum(Nombre)) %>%
    mutate(categorieJuridique = "Tout")
  ) %>%
  filter(Activité == "Enseignement") 

spoiler_table(df, trim = Inf)

print(df %>%
  ggplot(aes(y=reorder(categorieJuridique,Part),x=Part,fill=Activité)) +
  geom_col() +
  scale_x_continuous(labels=scales::percent) +
  theme(axis.title.y = element_blank(), plot.title = element_text(hjust=1)) +
  ggtitle("Part des entreprises dans le secteur Enseignement par statut") 
)
```



```{r categorie.part, fig.asp=3/4}
sirene %>%
  filter(etatAdministratifUniteLegale == "A") %>%
  summarise(Nombre = n(), .by=c(Activité,Categorie)) %>% 
  mutate(Part = Nombre/sum(Nombre),.by=Activité) %>%
  ggplot(aes(x=Categorie, y=Part,fill=Categorie)) + 
    geom_col() +
    #scale_x_discrete(limits=rev) +
    facet_wrap(Activité~., labeller = labeller(Activité = label_wrap_gen(25))) +
  theme(axis.text.x=element_blank())
```

```{r categorie.part2, fig.asp=3/4}
sirene %>%
  filter(etatAdministratifUniteLegale == "A") %>%
  filter(Categorie != "Privé individuel") %>%
  summarise(Nombre = n(), .by=c(Activité,Categorie)) %>% 
  mutate(Part = Nombre/sum(Nombre),.by=Activité) %>%
  ggplot(aes(x=Categorie, y=Part,fill=Categorie)) + 
    geom_col() +
    #scale_x_discrete(limits=rev) +
    #coord_cartesian(ylim=c(0,0.1)) +
    facet_wrap(Activité~., labeller = labeller(Activité = label_wrap_gen(25))) +
  theme(axis.text.x=element_blank())
```