---
title: "Immobilier"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggcpesrthemes)
theme_set(theme_cpesr() + theme(legend.position="right"))

theme_cpesr_setup(authors = "Julien Gossa", source = "SIES https://github.com/cpesr/RFC/blob/main/immobilier/immobilier.md")
```

Source : https://data.enseignementsup-recherche.gouv.fr/explore/dataset/fr-esr-patrimoine-immobilier-des-operateurs-de-l-enseignement-superieur/

```{r load}
imo <- read.csv2("../data/fr-esr-patrimoine-immobilier-des-operateurs-de-l-enseignement-superieur.csv", dec='.', na.strings = "") %>%
  mutate(
    Domaine.bat. = recode(Domaine.bat.,"PUBLIC" = "public"),
    Catégorie.ERP = recode(Catégorie.ERP,
                           "1re : au-dessus de 1500 personnes" = "1 : 1500- personnes",
                           "3e : de 301 à 700 personnes" = "3: 301-700 personnes",
                           "2e : de 701 à 1500 personnes" = "2: 701-1500 personnes",
                           "4e : 300 personnes et au-dessous, à l'exception des établissements compris dans la 5e catégorie" = "4: -300 personnes (hors 5)",
                           "5e : établissements accueillant un nombre de personnes inférieur au seuil dépendant du type d'établissement" = "5 : inférieur au seuil")
  )

colnames(imo)
```

```{r explo.fun, cache=TRUE}

explore <- function(var) {
  
  imo.explo <- imo %>%
    group_by(Année, var = !!sym(var)) %>%
    summarise(nb_bat = n())
  

  p1 <- imo.explo %>%
    ggplot(aes(x=Année,y=nb_bat,color=var)) +
      geom_line(size=1) + geom_point(shape=21,size=3,stroke=1, fill="white") +
      ylab(var)
  
  p2 <- imo.explo %>%
    arrange(Année) %>%
    group_by(var) %>%
    mutate(val100 = nb_bat / first(nb_bat) * 100) %>%
    na.omit() %>%
    ggplot(aes(x=Année,y=val100,color=var)) +
      geom_line(size=1) + geom_point(shape=21,size=3,stroke=1, fill="white") +
      ylab(var)

  p3 <- imo.explo %>%
    ggplot(aes(x=Année,y=nb_bat,fill=var)) +
      geom_area(color="white") +
      ylab(var)

  p4 <- imo.explo %>%
    ungroup() %>%
    filter(Année %in% range(Année)) %>%
    ggplot(aes(y=reorder(var,nb_bat,FUN=last),x=nb_bat,fill=var)) +
      geom_col(color="white") +
      facet_grid(Année~.) +
      ylab(var)
  
  cat("\n\n## ",var,"\n\n")
  print(p1)
  print(p2)
  print(p3)
  print(p4)
  cat("\n\n")

}
```

```{r explo.loop, results='asis'}
vars = c("Etat.santé","Type.bât.","Domaine.bat.","Propriétaire.bat.","Réglementation.générale","Catégorie.ERP","Type.ERP","Class..Monument.histo.","Etat.access.","Access..AdAP","Access..dérog.","Energie.class.","GES","Audit.energie","Bilan.carbone")
for(var in vars)
  explore(var)
```



## Classement GES

```{r class.ges, fig.asp=4/3}
imo %>% 
  filter(Année == 2022) %>%
  left_join(
    kpiESR::esr.etab %>% select(pid, etab=Etablissement, Groupe),
    by = c(Paysage_id = "pid")) %>%
  filter(Groupe == "Universités et assimilés") %>%
  group_by(etab, GES = fct_rev(as.factor(GES))) %>%
  summarise(Nombre.bâtiments = n()) %>%
  group_by(etab) %>%
  mutate(score = sum(ifelse(GES %in% c("G","F"), Nombre.bâtiments, 0), na.rm = TRUE)) %>%
  #filter(score!=0) %>%
  #View() 
  ggplot(aes(y=reorder(etab,score),x=Nombre.bâtiments, fill = GES, group=!is.na(GES))) + 
  geom_col() +
  scale_fill_brewer(palette="RdBu", na.value="grey50") +
  ggtitle("Nombre de bâtiments par classe GES dans les universités") +
  theme(axis.title.y = element_blank(), legend.position = "right", plot.title = element_text(hjust=1)) +
  cpesr_cap() 
  
```


## Propriétaires

```{r prop, fig.asp=16/9}
prop <- imo %>% 
  left_join(kpiESR::esr.etab,by = join_by(Paysage_id == pid)) %>%
  summarise(
     nb = n(),
    .by = c(Année,Sigle,Propriétaire.bat.,Groupe,PerimEx)
  ) %>% 
  mutate(ratio = n() / sum(nb), .by = c(Année,Sigle)) %>%
  filter(!is.na(Sigle))

prop %>% 
  filter(Année == max(Année)) %>%
  filter(Propriétaire.bat. == "Tiers") %>%
  ggplot(aes(x=ratio,y=reorder(Sigle,ratio),fill=Groupe)) +
  geom_col() +
  ggtitle("Ratio de bâtiment appartenant à un tiers")
```

```{r prop.univ, fig.asp=16/9}
prop %>% 
  filter(Année == max(Année)) %>%
  filter(Propriétaire.bat. == "Tiers") %>%
  filter(Groupe == "Universités et assimilés") %>%
  ggplot(aes(x=ratio,y=reorder(Sigle,ratio),fill=PerimEx)) +
  geom_col() +
  ggtitle("Ratio de bâtiment appartenant à un tiers")
```


```{r tiers, fig.asp=16/9}
tiers <- imo %>% 
  left_join(kpiESR::esr.etab,by = join_by(Paysage_id == pid)) %>%
  filter(Propriétaire.bat. == "Tiers") %>%
  summarise(
     Année = min(Année),
    .by = c(Sigle,Libellé.bât.ter,Type.bât., Domaine.bat.)
  ) 
```

```{r tiers.2017, results='asis'}
tiers %>%
  filter(Année == min(Année)) %>%
  summarise(nb = n(), .by = c(Année,Type.bât.,Domaine.bat.)) %>%
  arrange(-nb) %>%
  spoiler_table(trim = Inf, title = "En 2017")
```

```{r tiers.2018, results='asis'}
tiers %>%
  filter(Année > min(Année)) %>%
  summarise(nb = n(), .by = c(Type.bât.,Domaine.bat.)) %>%
  arrange(-nb) %>%
  spoiler_table(trim = Inf,title = "Nouveaux après 2017")
```