---
title: "Réussite"
author: "CPESR"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(dplyr.summarise.inform = FALSE)
knitr::opts_chunk$set(fig.asp = 9/16, fig.retina = 2)

library(tidyverse)
library(ggcpesrthemes)
theme_set(theme_cpesr())
theme_cpesr_setup(authors = "Julien Gossa", source = "https://github.com/cpesr/RFC/blob/main/EducNat/Reussite.md")
```

## Données 

## Données 

- https://data.education.gouv.fr/explore/dataset/fr-en-indicateurs-de-resultat-des-lycees-denseignement-general-et-technologique
- https://data.education.gouv.fr/explore/dataset/fr-en-indicateurs-de-resultat-des-lycees-denseignement-professionnels
- https://data.education.gouv.fr/explore/dataset/fr-en-dnb-par-etablissement

- https://data.education.gouv.fr/explore/dataset/fr-en-ips_ecoles_v2
- https://data.education.gouv.fr/explore/dataset/fr-en-ips_colleges
- https://data.education.gouv.fr/explore/dataset/fr-en-ips_lycees


```{r load.brevet}
percent_to_numeric <- function(x) {
  x <- gsub("%","",x)
  x <- gsub(",",".",x)
  as.numeric(x)
}
  

brevet <- read.csv2("../data/fr-en-dnb-par-etablissement.csv", dec='.') %>%
  mutate(Taux.de.réussite = percent_to_numeric(Taux.de.réussite))
colnames(brevet)
```

```{r load.legt}
legt <- read.csv2("../data/fr-en-indicateurs-de-resultat-des-lycees-denseignement-general-et-technologique.csv", dec='.')
colnames(legt)
```

```{r load.lp}
lp <- read.csv2("../data/fr-en-indicateurs-de-resultat-des-lycees-denseignement-professionnels.csv", dec='.')
colnames(lp)
```


```{r load.ips}
ips.ecole <- read.csv2("../data/fr-en-ips_ecoles_v2.csv", dec='.')
ips.college <- read.csv2("../data/fr-en-ips_colleges.csv", dec='.')
ips.lycee <- read.csv2("../data/fr-en-ips_lycees.csv", dec='.')
ips <- bind_rows(
  ips.ecole %>% mutate(Niveau = "Ecole"),
  ips.college %>% mutate(Niveau = "Collège"),
  ips.lycee %>% 
    mutate(
      Code.du.département = as.character(Code.du.département),
      Code.INSEE.de.la.commune = as.character(Code.INSEE.de.la.commune),
      Niveau = "Lycée")
    # rename(
    #   Académie = academie,
    #   Département = departement,
    #   UAI = uai,
    #   Nom.de.l.établissment = nom_de_l_etablissment,
    #   Code.INSEE.de.la.commune = code_insee_de_la_commune,
    #   Nom.de.la.commune = nom_de_la_commune,
    #   Secteur = secteur,
    #   IPS = ips_ensemble_gt_pro
    # ) %>% 
  ) %>%
  mutate(
    Niveau = factor(Niveau, levels = c("Ecole","Collège","Lycée")),
    Rentrée = as.numeric(str_sub(Rentrée.scolaire,1,4))
  )

colnames(ips)
```

## Explorations

### Collèges 

```{r college.reussite}
college.ips <- inner_join(
  brevet %>% filter(Session == 2021),
  ips %>% filter(Rentrée == 2021),
  by = join_by(Numero.d.etablissement == UAI)
) 

write.csv2(college.ips, "college_ips.csv", row.names = FALSE)

college.ips %>%
  ggplot(aes(x=IPS,y=Taux.de.réussite)) + geom_point()
```

```{r}
college.ips %>%
  filter(!is.na(IPS)) %>%
  mutate(IPS.cut = cut(IPS, 
                       breaks = c(-Inf,75,100,125,Inf), 
                       labels = c("Très défavorisé\n(IPS<75)","Défavorisé\n(75<IPS<100)","Favorisé\n (100<IPS<125)","Très favorisé\n(IPS>125)"))) %>%
  ggplot(aes(x=IPS.cut,y=Taux.de.réussite,fill=IPS.cut)) + 
  geom_boxplot() +
  scale_fill_brewer(palette = "RdBu") +
  labs(title = "Taux de réussite au Brevet selon l'indice de position sociale (IPS)",
       subtitle = "IPS moyen des collèges de France, session 2021",
       x = "IPS moyen de l'établissement",
       y = "Taux de réussite au Brevet") +
  theme(legend.position = "none") +
  cpesr_cap()

```


```{r}
college.ips %>%
  filter(!is.na(IPS)) %>%
  mutate(IPS.cut = cut(IPS, 
                       breaks = c(-Inf,75,100,125,Inf), 
                       labels = c("Très défavorisé\n(IPS<75)","Défavorisé\n(75<IPS<100)","Favorisé\n (100<IPS<125)","Très favorisé\n(IPS>125)"))) %>%
  summarize(
    Absents = sum(Inscrits - Presents),
    Refusés = sum(Presents - Admis),
    .by = IPS.cut
  ) %>% pivot_longer(cols = c(Absents,Refusés), names_to = "Type", values_to = "Nombre") %>%
  ggplot(aes(x=IPS.cut,y=Nombre,fill=Type)) + 
  geom_col() +
  scale_fill_brewer(palette = "Dark2") +
  labs(title = "Nombre d'élèves échouant au Brevet selon l'indice de position sociale",
       subtitle = "IPS moyen des collèges de France, session 2021",
       x = "IPS moyen de l'établissement",
       y = "Taux de réussite au Brevet") +
  cpesr_cap()

```


```{r college.tb}
college.ips %>%
  mutate(taux.TB = Admis.Mention.très.bien / Inscrits) %>%
  ggplot(aes(x=IPS,y=taux.TB)) + geom_point()
```



```{r college.btb}
college.ips %>%
  mutate(taux.BTB = (Admis.Mention.très.bien+Admis.Mention.bien) / Inscrits) %>%
  ggplot(aes(x=IPS,y=taux.BTB)) + geom_point(size=0.1) + geom_smooth() +
  scale_y_continuous(labels = scales::percent, name = "Taux de mention B ou TB au DNB") +
  xlab("Indice de position sociale (IPS)") +
  ggtitle("Collèges de France", subtitle ="selon leur taux de mention bien ou très bien au DNB et leur indice de position sociale") + 
  cpesr_cap()
```


```{r college.btb.et}
college.ips %>%
  mutate(taux.BTB = (Admis.Mention.très.bien+Admis.Mention.bien) / Inscrits) %>%
  ggplot(aes(x=Ecart.type.de.l.IPS,y=taux.BTB)) + geom_point(size=0.1) + geom_smooth() +
  scale_y_continuous(labels = scales::percent, name = "Taux de mention B/TB au DNB") +
  xlab("Ecart-type de l'Indice de position sociale (IPS)") +
  ggtitle("Collèges de France", subtitle ="selon leur taux de mention B ou TB  au DNB et l'écart-type de l'indice de position sociale")
```

```{r college.inscrits}
college.ips %>%
  ggplot(aes(x=IPS,y=Inscrits)) + geom_point(size=0.1) + geom_smooth() +
  xlab("Ecart-type de l'Indice de position sociale (IPS)") 
```




### Lycées 

```{r lycee.reussite}
lycee.ips <- inner_join(
  legt %>% filter(Annee == 2021),
  ips %>% filter(Rentrée == 2020),
  by = c("UAI")
) 

lycee.ips %>%
  ggplot(aes(x=IPS,y=Taux.de.reussite...Toutes.series)) + geom_point()
```

```{r lycee.mention}
lycee.ips %>%
  ggplot(aes(x=IPS,y=Taux.de.mentions...Toutes.series/100)) + geom_point(size=0.1) + geom_smooth() +
  scale_y_continuous(labels = scales::percent, name = "Taux de mention au Bac") +
  xlab("Indice de position sociale (IPS)") +
  ggtitle("Lycées d'enseignement général et technologique de France", subtitle ="selon leur taux de mention au Bac et leur indice de position sociale") +
  cpesr_cap()
```


```{r lycee.taille}
lycee.ips %>%
  ggplot(aes(x=IPS,y=Presents...Toutes.series)) + geom_point(size=0.1) + geom_smooth() +
  cpesr_cap()
```



### Strasbourg

```{r college.btb.stras, fig.asp=3/4}
college.ips %>%
  filter(Session == 2021, Libellé.académie == "STRASBOURG") %>%
  mutate(taux.BTB = (Admis.Mention.très.bien+Admis.Mention.bien) / Inscrits) %>%
  mutate(Ville = ifelse(Libellé.commune == "STRASBOURG","Strasbourg","Autre")) %>%
  mutate(Collège = ifelse(Libellé.commune == "STRASBOURG",Patronyme,NA)) %>%
  ggplot(aes(x=IPS,y=taux.BTB,color=Ville, size=Ville)) + 
  geom_point() +
  ggrepel::geom_text_repel(aes(label=Collège), size=2, color = "blue", force = 50) +
  scale_y_continuous(labels = scales::percent, name = "Taux de mention B ou TB au DNB") +
  scale_size_manual(values=(c(1,2))) +
  scale_color_manual(values=(c("grey","blue"))) +
  xlab("Indice de position sociale (IPS)") +
  ggtitle("Collèges de l'académie de Strasbourg", subtitle ="selon leur taux de mention bien ou très bien au DNB et leur indice de position sociale") + 
  cpesr_cap()
```



### Aix-Marseille

```{r college.btb.aixmars, fig.asp=3/4}
college.ips %>%
  filter(Session == 2021, Libellé.académie == "AIX-MARSEILLE") %>%
  mutate(taux.BTB = (Admis.Mention.très.bien+Admis.Mention.bien) / Inscrits) %>%
  mutate(Ville = ifelse(Libellé.commune %in% c("GEMENOS","ROQUEVAIRE","AUBAGNE"), str_to_sentence(Libellé.commune),"Autre")) %>%
  mutate(Collège = ifelse(Ville != "Autre",Patronyme,NA)) %>%
  ggplot(aes(x=IPS,y=taux.BTB,color=Ville, size=Ville)) + 
  geom_point() +
  ggrepel::geom_text_repel(aes(label=Collège), size=2, color = "black", force = 50) +
  scale_y_continuous(labels = scales::percent, name = "Taux de mention B ou TB au DNB") +
  scale_size_manual(values=(c(2,1,2,2))) +
  #scale_color_manual(values=(c("grey","blue"))) +
  xlab("Indice de position sociale (IPS)") +
  ggtitle("Collèges de l'académie de Aix-Marseille", subtitle ="selon leur taux de mention bien ou très bien au DNB et leur indice de position sociale") + 
  cpesr_cap()
```



### Aix-Marseille

```{r college.btb.anse, fig.asp=3/4}
college.ips %>%
  filter(Session == 2021, Libellé.académie == "LYON") %>%
  mutate(taux.BTB = (Admis.Mention.très.bien+Admis.Mention.bien) / Inscrits) %>%
  mutate(Ville = ifelse(Libellé.commune %in% c("ANSE"), str_to_sentence(Libellé.commune),"Autre")) %>%
  mutate(Collège = ifelse(Ville != "Autre",Patronyme,NA)) %>%
  ggplot(aes(x=IPS,y=taux.BTB,color=Ville, size=Ville)) + 
  geom_point() +
  ggrepel::geom_text_repel(aes(label=Collège), size=2, color = "black", force = 50) +
  scale_y_continuous(labels = scales::percent, name = "Taux de mention B ou TB au DNB") +
  scale_size_manual(values=(c(2,1,2,2))) +
  #scale_color_manual(values=(c("grey","blue"))) +
  xlab("Indice de position sociale (IPS)") +
  ggtitle("Collèges de l'académie du Rhone", subtitle ="selon leur taux de mention bien ou très bien au DNB et leur indice de position sociale") + 
  cpesr_cap()
```


