---
title: "Choix spécialités Lycée "
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
library(tidyverse)
library(ggrepel)
library(ggcpesrthemes)
```

## Données sources

Les données accompagnent les notes de la DEPP :

- https://www.education.gouv.fr/choix-de-trois-specialites-en-premiere-generale-la-rentree-2019-15-combinaisons-pour-80-des-eleves-3245
- https://www.education.gouv.fr/la-rentree-2020-les-eleves-de-terminale-precisent-leur-choix-de-parcours-307016

```{r data}
spe.2019.1 <- read.csv("Spécialités-2019-Première.csv", na.strings = c("VALEUR MANQUANTE")) %>%
  transmute(
    Bac = 2021,
    Niveau = "Première",
    Spécialités = toupper(iconv(Première.2019, from="UTF-8", to="ASCII//TRANSLIT")),
    Effectifs = Effectifs
    )

spe.2020.T <- read.csv("Spécialités-2020-Terminale.csv") %>%
  transmute(
    Bac = 2021,
    Niveau = "Terminale",
    Spécialités = Terminale.2020,
    Effectifs = Effectifs
    )

spe.2020.1 <- read.csv("Spécialités-2020-Première.csv") %>%
  transmute(
    Bac = 2022,
    Niveau = "Première",
    Spécialités = Première.2020,
    Effectifs = Effectifs
    )

spe <- bind_rows(spe.2019.1,spe.2020.T,spe.2020.1) %>%
  mutate(
    Spécialités.sep = str_split(Spécialités, pattern=" ")
  )

spe.noms <- unique(c(unlist(spe$Spécialités.sep)))

label_effectifs <- function(x) {
  paste0(round(x/1000),"k")
}
```


```{r functions}

stat.global <- function() {
  spe.disc %>%
  group_by(Niveau,Discipline) %>%
  summarise(
    Effectifs = sum(Effectifs)) %>%
  mutate(Niveau=recode(Niveau,"Première" = "1ère")) %>%
  ggplot(aes(x=Niveau,y=Effectifs, fill=Discipline)) + 
    geom_col(color="black") +
    geom_text(aes(label=label_effectifs(Effectifs)), position = position_stack(vjust = .5)) +
    coord_polar(theta = "y") +
    scale_fill_brewer(
      palette = "Set1",
      labels=c(paste("Sans ",discipline.cible),paste("Avec ",discipline.cible))) +
    geom_text(aes(label=Niveau),y=0,nudge_x =-0.1,color="white",stat = "unique",hjust=-0.1) +
    # annotate("text", x=1,y=0,label="Terminale") +
    # annotate("text", x=1,y=0,label="Terminale") +
    theme_cpesr_cap() + theme(
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      axis.text.x = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      panel.grid.major.y  = element_blank()
      )
}

stat.cospe <- function() {
df <- spe.disc %>%
  filter(Discipline) %>%
  separate_rows(Spécialités, sep=" ") 

df.disc <- df %>%
  filter(Spécialités == discipline.cible) %>%
  group_by(Niveau) %>%
  summarise(Effectifs.disc = sum(Effectifs))

df.rank <- df %>%
  filter(Spécialités != discipline.cible, Niveau == "Terminale") %>%
  group_by(Spécialités) %>%
  summarise(Effectifs = sum(Effectifs)) %>%
  transmute(
    Spécialités = Spécialités,
    Rang = rank(desc(Effectifs)))

df %>%
  filter(Spécialités != discipline.cible) %>%
  group_by(Niveau, Spécialités) %>%
  summarise(Effectifs = sum(Effectifs)) %>% 
  merge(df.rank) %>% 
  mutate(Spécialités = case_when(
    Rang <= 10 ~ Spécialités,
    TRUE ~ "Autres"
  )) %>% 
  group_by(Niveau, Spécialités) %>%
  summarise(
    Effectifs = sum(Effectifs),
    Rang = min(Rang)) %>% 
  merge(df.disc) %>%
  mutate(Ratio = Effectifs/Effectifs.disc) %>%
  ggplot(aes(x=reorder(Spécialités, Effectifs),y=Effectifs,fill=Niveau)) +
    geom_col(position="identity",color="black") +
    geom_text(aes(label=scales::percent(Ratio)), position = "identity", direction ="x", hjust=-0.1) +
    coord_flip(clip="off") +
    scale_fill_brewer(
      palette = "Paired",
      labels=c("Première","Première et Terminale")) +
    theme_cpesr_cap() + theme(
      plot.margin = margin(0,10,0,0),
      axis.title.y = element_blank(),
      panel.grid.major.y = element_blank(),
      panel.grid.major.x = element_line(color="grey",size=0.2))
}
```


### Test Maths

```{r maths.data}
bac.cible <- 2021
discipline.cible <- "MATHS"

spe.disc <- spe %>%
  filter(Bac == bac.cible) %>%
  mutate(Discipline = str_detect(Spécialités,discipline.cible))
```

```{r maths.global}
stat.global()
```

```{r maths.cospe}
stat.cospe()
```


### Test SES

_Est-ce que SES est plus adapté que Maths pour présenter les visualisations ?_

```{r SES.data}
bac.cible <- 2021
discipline.cible <- "SES"

spe.disc <- spe %>%
  filter(Bac == bac.cible) %>%
  mutate(Discipline = str_detect(Spécialités,discipline.cible))
```

```{r SES.global}
stat.global()
```

```{r SES.cospe}
stat.cospe()
```


## Parcoursup

```{r pspeload}

spés <- list(
  "Arts"="Arts", 
  "Biologie-Ecologie"="Bio-Eco", 
  "Humanités, Littérature et Philosophie" = "Humanités", 
  "Histoire,Géographie, Géopolitique, Sciences politiques" = "Histoire-Géo.", 
  "Littératures, langues et culture de l'antiquité" = "LLCA",
  "Langues, Littératures et Cultures Etrangères et Régionales" = "LLCER", 
  "Mathématiques" = "Math.", 
  "Numérique et Sciences Informatiques" = "NSI", 
  "Physique-Chimie" = "PC", 
  "Sciences économiques et sociales" = "SES", 
  "Sciences de la vie et de la terre" = "SVT",
  "Sciences de l'ingénieur" = "SI")

pspe <- read.csv2("fr-esr-parcoursup-enseignements-de-specialite-bacheliers-generaux.csv", dec = ".") %>%
  setNames(c("Spécialités","Formation","Candidatures","Propositions","Admissions")) %>%
  mutate(
    Taux.proposition = Propositions/Candidatures,
    Taux.admission = Admissions/Candidatures 
  ) %>%
  separate(Spécialités,into=c("Spécialité.1","Spécialité.2"),sep="&",remove=FALSE) %>%
  mutate(
   Spécialité.1 = factor(Spécialité.1,levels=names(spés),labels=spés),
   Spécialité.2 = factor(Spécialité.2,levels=names(spés),labels=spés),
  ) %>%
  mutate(
    Spécialités = paste0(Spécialité.1," & ",Spécialité.2)
  )

type.pal = RColorBrewer::brewer.pal(6,"Paired")[c(6,5,4)]
  
```


```{r pspe.tp, fig.height=6, fig.width=5}
pspe %>% 
  filter(Formation == "Ensemble des candidats bacheliers" ) %>%
  filter(Candidatures > 100) %>%
  ggplot(aes(x=reorder(Spécialités,Taux.proposition,FUN=median),y=Taux.proposition)) +
  geom_point() +
  coord_flip() +
  theme_cpesr()
```

```{r pspe.ta, fig.height=6, fig.width=5}
pspe %>% 
  filter(Formation == "Ensemble des candidats bacheliers" ) %>%
  filter(Candidatures > 100) %>%
  ggplot(aes(x=reorder(Spécialités,Taux.admission,FUN=median),y=Taux.admission)) +
  geom_point() +
  coord_flip() +
  theme_cpesr()
```

```{r pspe.all, fig.height=10, fig.width=7}
pspe %>% 
  filter(Formation == "Ensemble des candidats bacheliers" ) %>%
  mutate(
    Proposition.acceptée = Admissions,
    Proposition.refusée = Propositions - Admissions,
    Sans.proposition = Candidatures - Propositions
  ) %>%
  pivot_longer(c(Proposition.acceptée, Proposition.refusée, Sans.proposition), names_to = "Type", values_to = "Nombre") %>%
  mutate(Type = fct_rev(factor(Type,
                       levels=c("Proposition.acceptée","Proposition.refusée","Sans.proposition"),
                       labels=c("Proposition acceptée","Proposition refusée","Sans proposition")))) %>%
  #filter(Candidatures > 100) %>%
  mutate(vj = case_when(Type == "Proposition acceptée" ~ 0, Type=="Proposition refusée" ~ 1, TRUE ~ 1)) %>%
  ggplot(aes(x=reorder(Spécialités,Taux.admission,FUN=median),y=Nombre)) +
  geom_col(aes(fill=Type),position="fill") +
  geom_text(data= . %>% select(Spécialités,Taux.admission,Candidatures) %>% unique(), y=0.5,
    aes(label=format(Candidatures, big.mark=" ")),stat="unique", size=3, color="white", hjust=1) +
  coord_flip() +
  scale_fill_manual(values=type.pal) +
  theme_cpesr()
```

```{r pspe.all.spe, fig.height=6, fig.width=7}
pspe %>% 
  filter(Formation == "Ensemble des candidats bacheliers" ) %>%
  pivot_longer(c(Spécialité.1,Spécialité.2),names_to = "Spé", values_to = "Spécialité") %>%
  group_by(Spécialité) %>%
  summarise(across(c(Candidatures,Propositions,Admissions),sum)) %>%
  mutate(Taux.admission=Admissions/Candidatures) %>%
  mutate(
    Proposition.acceptée = Admissions,
    Proposition.refusée = Propositions - Admissions,
    Sans.proposition = Candidatures - Propositions
  ) %>%
  ungroup() %>%
  pivot_longer(c(Proposition.acceptée, Proposition.refusée, Sans.proposition), names_to = "Type", values_to = "Nombre") %>%
  mutate(Type = fct_rev(factor(Type,
                       levels=c("Proposition.acceptée","Proposition.refusée","Sans.proposition"),
                       labels=c("Proposition acceptée","Proposition refusée","Sans proposition")))) %>% 
  ggplot(aes(x=reorder(Spécialité,Taux.admission),y=Nombre)) +
  geom_col(aes(fill=Type),position="fill") +
  geom_text(data= . %>% select(Spécialité,Taux.admission,Candidatures) %>% unique(), y=0.5,
    aes(label=format(Candidatures, big.mark=" ")),stat="unique", size=3, color="white", hjust=1) +
  coord_flip() +
  scale_fill_manual(values=type.pal) +
  theme_cpesr()
```



```{r pspe.all.all}
pspe %>% 
  filter(Formation == "Ensemble des candidats bacheliers" ) %>%
  summarise(across(c(Candidatures,Propositions,Admissions),sum)) %>%
  mutate(
    Proposition.acceptée = Admissions,
    Proposition.refusée = Propositions - Admissions,
    Sans.proposition = Candidatures - Propositions
  ) %>%
  pivot_longer(c(Proposition.acceptée, Proposition.refusée, Sans.proposition), names_to = "Type", values_to = "Nombre") %>%
  mutate(Type = fct_rev(factor(Type,
                       levels=c("Proposition.acceptée","Proposition.refusée","Sans.proposition"),
                       labels=c("Proposition acceptée","Proposition refusée","Sans proposition")))) %>%
  ggplot(aes(x=Type,y=Nombre,fill=Type)) +
  geom_col() +
  coord_flip() +
  geom_text(aes(label=Nombre),position=position_stack(vjust = .5), size=3) +
  scale_fill_manual(values=type.pal) +
  theme_cpesr()
```
