---
title: "Concours MCF"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(ggthemes)
library(ggbeeswarm)
library("gridExtra")
library(ggcpesrthemes)
data_CNU = read.table("DB_CNU_QualificationRecrutements_20201123.csv", h=T, sep=";")
```


## Description des données 

- Nombre d'observations : `r nrow(data_CNU)`
- Variables : 
```{r vars}
colnames(data_CNU)
```
- Période : `r range(data_CNU$Annee)`


## Nombre de candidatures par candidat aux postes MCF
```{r data.setup}
cnu <- data_CNU %>%
  mutate(
    #Annee = as.factor(Annee),
    candidatures.par.candidat.MCF = Candidatures.MCF / Candidats.MCF)
```

### Vision globale par grande discipline et groupes CNU
```{r candidatures.par.candidat.MCF.1, fig.width=12, fig.asp=9/16}
cnu %>%
  drop_na(candidatures.par.candidat.MCF) %>%
    ggplot(aes(x=candidatures.par.candidat.MCF, y=GroupeCNU, color=Annee)) +
    geom_jitter(width = 0, height = 0.15) +
    scale_x_continuous(breaks=seq(0,30,2)) +
    facet_grid(GrandeDisciplineCNU~., scales="free", space="free") +
    theme_cpesr_cap(authors=c("Florent Figon"), licence="CC BY-SA") +
    theme(strip.text.y = element_text(size = 7.5)) +
    theme(legend.position = "right") +
    scale_color_gradient(low="#E69F00", high="#009E73") +
    labs(title="Concours MCF, de 2013 à 2019", y ="Grandes disciplines CNU", x = "Nombre moyen de candidatures aux concours MCF par candidat (par section et par an)")
```

### Evolution de 2013 à 2019 toutes sections confondues
```{r candidatures.par.candidat.MCF.2}
cnu %>%
  drop_na(candidatures.par.candidat.MCF) %>%
    ggplot(aes(x=as.factor(Annee), y=candidatures.par.candidat.MCF)) +
    geom_boxplot() +
    theme_cpesr_cap(authors=c("Florent Figon"), 
      licence="CC BY-SA")
```

### Evolution de 2013 à 2019 par grande discipline
```{r candidatures.par.candidat.MCF.3}
cnu %>%
  drop_na(candidatures.par.candidat.MCF) %>%
    ggplot(aes(x=as.factor(Annee), y=candidatures.par.candidat.MCF)) +
    geom_boxplot() +
    facet_wrap(.~GrandeDisciplineCNU, scale="free") +
    theme_cpesr_cap(authors=c("Florent Figon"), 
      licence="CC BY-SA")
```