---
title: "IUT DUT/BUT"
author: "CPESR"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(dplyr.summarise.inform = FALSE)
knitr::opts_chunk$set(fig.asp = 9/16, fig.retina = 2)

library(tidyverse)
library(ggcpesrthemes)
theme_set(theme_cpesr())
theme_cpesr_setup(authors = "Julien Gossa", source = "https://github.com/cpesr/RFC/")

load("ps.RData")
```

## Données 

```{r load}
iut <- ps %>% filter(Filière.de.formation.très.agrégée == "DUT_BUT") %>%
  mutate(Filière = coalesce(Filière.de.formation.détaillée.1, Filière.de.formation.détaillée.bis, Filière.de.formation.détaillée)) %>%
  filter(Session >= 2018)

iut %>%
  summarise(across(
    c(Filière.de.formation.très.agrégée, Filière,
      Effectif.des.admis.néo.bacheliers,
      Effectif.des.admis.néo.bacheliers.généraux,
      Effectif.des.admis.néo.bacheliers.technologiques,
      Effectif.des.admis.néo.bacheliers.professionnels,
      Effectif.des.autres.candidats.admis),
    ~ sum(!is.na(.x))), .by=Session)
```

## Check

```{r, fig.asp=16/9}
iut %>%
  summarise(nb=n(), .by=c(Session,Filière)) %>% 
  ggplot(aes(x=Session,y=Filière,color=nb)) + geom_point()
```

```{r, fig.asp=3/4}
iut <- iut %>%
  mutate(Filière = case_when(
    str_detect(Filière,"de commercialisation") ~ "TC",
    str_detect(Filière,"formation communication") ~ "IC",
    str_detect(Filière,"génie des matériaux") ~ "SGM",
    str_detect(Filière,"informatique décisionnelle|données") ~ "STID",
    str_detect(Filière,"Réseaux et télécom") ~ "RT",
    str_detect(Filière,"Qualité, logistique") ~ "QLIO",
    str_detect(Filière,"Packaging") ~ "PEC",
    str_detect(Filière,"multimédia") ~ "MMI",
    str_detect(Filière,"thermique|Transition") ~ "MTEE",
    str_detect(Filière,"Mesures physiques") ~ "MP",
    str_detect(Filière,"énie biologique") ~ "GB",
    str_detect(Filière,"arrières sociales") ~ "CS",
    str_detect(Filière,"arrières juridiques") ~ "CJ",
    str_detect(Filière,"ransport") ~ "MLT",
    str_detect(Filière,"énie civil") ~ "GC",
    str_detect(Filière,"administrative et commerciale") ~ "GECO",
    str_detect(Filière,"mécanique et productique") ~ "GMP",
    str_detect(Filière,"entreprises et des administrations") ~ "GEA",
    str_detect(Filière,"électrique") ~ "GEII",
    str_detect(Filière,"procédés") ~ "GCGP",
    str_detect(Filière,"industriel") ~ "GIM",
    str_detect(Filière,"Sécurité") ~ "HSE",
    str_detect(Filière,"Informatique") ~ "Info",
    .default = Filière
  )) 

iut %>%
  summarise(nb=n(), .by=c(Session,Filière)) %>% 
  ggplot(aes(x=Session,y=Filière,color=nb)) + geom_point()
```

# admis

```{r}
iut.admis <- iut %>%
  pivot_longer(
    c(Effectif.des.admis.néo.bacheliers.généraux,
      Effectif.des.admis.néo.bacheliers.technologiques,
      Effectif.des.admis.néo.bacheliers.professionnels,
      Effectif.des.autres.candidats.admis),
    names_to = "Admis", values_to = "Effectifs") %>%
  mutate(Admis = factor(Admis,
                        levels = c("Effectif.des.admis.néo.bacheliers.généraux",
                                   "Effectif.des.admis.néo.bacheliers.technologiques",
                                   "Effectif.des.admis.néo.bacheliers.professionnels",
                                   "Effectif.des.autres.candidats.admis"),
                        labels = c("Néobac généraux", 
                                   "Néobac techno", 
                                   "Néobac pro", 
                                   "Autres"))) %>%
  filter(!is.na(Effectifs)) %>%
  summarize(Effectifs = sum(Effectifs),
            .by=c(Session,Établissement,Filière, Admis, Taux.d.accès))

```
## Explorations

```{r}
iut.admis %>%
  summarize(Effectifs = sum(Effectifs), .by=c(Session, Admis)) %>%
  ggplot(aes(x=Session,y=Effectifs,color=Admis)) + geom_line(size=1)
```


```{r}
iut.admis %>%
  summarize(Effectifs = sum(Effectifs), .by=c(Session, Admis)) %>%
  mutate(val100 = Effectifs / first(Effectifs) * 100, .by=Admis) %>%
  ggplot(aes(x=Session,y=val100,color=Admis)) + geom_line(size=1)
```

## Substitution BT/BG

```{r, fig.asp=4/3}
indice.BGBT.Filière <- iut %>%
  summarize(BG = sum(Effectif.des.admis.néo.bacheliers.généraux, na.rm = TRUE), 
            BT = sum(Effectif.des.admis.néo.bacheliers.technologiques, na.rm = TRUE), 
            admis = sum(admis, na.rm = TRUE),
            .by=c(Session, Filière)) %>%
  arrange(Session) %>%
  mutate(diff = BG/admis-BT/admis) %>% 
  summarise(BGBT = last(diff) - first(diff), 
            diff = (last(BG) - last(BT))/last(admis),
            .by = c(Filière)) %>%
  arrange(diff)
```


```{r, fig.asp=4/3}
iut.admis %>%
  mutate(Filière = factor(Filière, levels = indice.BGBT.Filière$Filière)) %>%
  summarize(
    Effectifs = sum(Effectifs),
    .by=c(Session, Admis, Filière)) %>%
  mutate(val100 = Effectifs / first(Effectifs) * 100, .by=Admis) %>% 
  ggplot(aes(x=Session,y=Effectifs,color=Admis,size=Admis)) + geom_line() +
  facet_wrap(~Filière, scales="free_y") +
  scale_size_manual(values=c(0.6,0.6,0.2,0.2)) +
  scale_x_continuous(breaks = c(2020))
```

```{r, fig.asp=9/16}
iut.admis %>%
  mutate(Filière = factor(Filière, levels = indice.BGBT.Filière$Filière)) %>%
  summarize(
    Effectifs = sum(Effectifs),
    .by=c(Session, Admis, Filière)) %>%
  filter(Admis %in% c("Néobac généraux","Néobac techno")) %>%
  ggplot(aes(x=Session,y=Effectifs,color=Admis,size=Session,alpha=Session)) + 
  geom_line() + 
  geom_point(data = ~ slice_tail(.x,n=1, by = c(Admis,Filière)), size=1) +
  facet_wrap(~Filière, scales="free_y", nrow=2) +
  scale_size_continuous(range=c(0.8,0.8), guide=NULL) +
  scale_alpha_continuous(range=c(0.4,1), guide=NULL) +
  scale_x_continuous(breaks = c(2020)) +
  expand_limits(y=0) +
  theme(axis.text.y = element_blank(), 
        panel.grid.major.y = element_blank(), panel.grid.minor.y = element_blank()) +
  labs(title = "Admissions Parcoursup des néobachelier⋅es généraux et technologiques",
       y="Admissions")
  
```



```{r, fig.asp=4/3}
pasteEbabFil <- function(e,f) {
  paste(gsub("(?: - )?(?:Site|Antenne).*$","",e), f, sep="\n")
}

indice.BGBT.Filière <- iut %>%
  summarize(BG = sum(Effectif.des.admis.néo.bacheliers.généraux, na.rm = TRUE), 
            BT = sum(Effectif.des.admis.néo.bacheliers.technologiques, na.rm = TRUE), 
            admis = sum(admis, na.rm = TRUE),
            .by=c(Session, Établissement, Filière)) %>%
  arrange(Session) %>%
  mutate(diff = BG/admis-BT/admis) %>% 
  summarise(BGBT = last(diff) - first(diff), 
            .by = c(Établissement, Filière)) %>%
  arrange(BGBT)

indice.BGBT.Filière.top <- bind_rows(
  indice.BGBT.Filière %>% head(4),
  indice.BGBT.Filière %>% tail(4)) %>%
  mutate(EtabFil = pasteEbabFil(Établissement, Filière))
```


```{r, fig.asp=9/16}
iut.admis %>%
  mutate(EtabFil = pasteEbabFil(Établissement, Filière)) %>%
  filter(EtabFil %in% indice.BGBT.Filière.top$EtabFil) %>%
  filter(Admis %in% c("Néobac généraux","Néobac techno")) %>%
  mutate(EtabFil = factor(EtabFil, levels = indice.BGBT.Filière.top$EtabFil)) %>%
  summarize(
    Effectifs = sum(Effectifs),
    .by=c(Session, Admis, EtabFil)) %>%
  mutate(val100 = Effectifs / first(Effectifs) * 100, .by=Admis) %>% 
  ggplot(aes(x=Session,y=Effectifs,color=Admis,size=Session,alpha=Session)) + 
  geom_line() +
  geom_point(data = ~ slice_tail(.x,n=1, by = c(Admis,EtabFil)), size=2) +
  facet_wrap(~EtabFil, scales="free_y", nrow=2) +
  scale_size_continuous(range=c(0.8,0.8), guide=NULL) +
  scale_alpha_continuous(range=c(0.4,1), guide=NULL) +
  scale_x_continuous(breaks = c(2020)) +
  labs(title = "Admissions Parcoursup des néobachelier⋅es généraux et technologiques",
       y="Admissions")

```



## Places vs. Admis

```{r, fig.asp=9/16}
iut %>%
  summarise(
    places = sum(places), 
    admis = sum(admis),
    admis.PP = sum(Effectif.des.admis.en.phase.principale),
    admis.PC = sum(Effectif.des.admis.en.phase.complémentaire),
    .by=Session) %>%
  pivot_longer(c(places,admis, admis.PP), values_to = "effectif", names_to = "indicateur") %>%
  ggplot(aes(x=Session,y=effectif,color=indicateur)) + geom_line()
```


```{r, fig.asp=9/16}
iut %>%
  summarise(
    places = sum(places), 
    admis = sum(admis),
    admis.PP = sum(Effectif.des.admis.en.phase.principale),
    admis.PC = sum(Effectif.des.admis.en.phase.complémentaire),
    .by=c(Session,Filière)) %>%
  pivot_longer(c(places,admis, admis.PP), values_to = "effectif", names_to = "indicateur") %>%
  ggplot(aes(x=Session,y=effectif,color=indicateur)) + geom_line() +
  facet_wrap(.~Filière, scales="free_y")
```



```{r, fig.asp=9/16}
iut %>%
  summarise(
    classés.BG = sum(Effectif.des.candidats.néo.bacheliers.généraux.classés.par.l.établissement),
    classés.BT = sum(Effectif.des.candidats.néo.bacheliers.technologiques.classés.par.l.établissement),
    classés.BP = sum(Effectif.des.candidats.néo.bacheliers.professionnels.classés.par.l.établissement),
    .by=Session) %>%
  pivot_longer(c(classés.BG, classés.BT, classés.BP), values_to = "effectif", names_to = "indicateur") %>%
  ggplot(aes(x=Session,y=effectif,color=indicateur)) + geom_line()
```


```{r, fig.asp=9/16}
iut %>%
  summarise(
    classés.BG = sum(Effectif.des.candidats.néo.bacheliers.généraux.classés.par.l.établissement),
    classés.BT = sum(Effectif.des.candidats.néo.bacheliers.technologiques.classés.par.l.établissement),
    classés.BP = sum(Effectif.des.candidats.néo.bacheliers.professionnels.classés.par.l.établissement),
    .by=c(Session,Filière)) %>%
  pivot_longer(c(classés.BG, classés.BT, classés.BP), values_to = "effectif", names_to = "indicateur") %>%
  ggplot(aes(x=Session,y=effectif,color=indicateur)) + geom_line() +
  facet_wrap(.~Filière, scales="free_y")
```



```{r, fig.asp=9/16}
iut %>%
  summarise(
    mention.BG = sum(Effectif.des.admis.néo.bacheliers.généraux.ayant.eu.une.mention.au.bac),
    mention.BT = sum(Effectif.des.admis.néo.bacheliers.technologiques.ayant.eu.une.mention.au.bac),
    mention.BP = sum(Effectif.des.admis.néo.bacheliers.professionnels.ayant.eu.une.mention.au.bac),
    .by=Session) %>%
  pivot_longer(c(mention.BG,mention.BT,mention.BP), values_to = "effectif", names_to = "indicateur") %>%
  ggplot(aes(x=Session,y=effectif,color=indicateur)) + geom_line()
```


```{r, fig.asp=9/16}
iut %>%
  summarise(
    mention.BG = sum(Effectif.des.admis.néo.bacheliers.généraux.ayant.eu.une.mention.au.bac),
    mention.BT = sum(Effectif.des.admis.néo.bacheliers.technologiques.ayant.eu.une.mention.au.bac),
    mention.BP = sum(Effectif.des.admis.néo.bacheliers.professionnels.ayant.eu.une.mention.au.bac),
    .by=c(Session,Filière)) %>%
  pivot_longer(c(mention.BG,mention.BT,mention.BP), values_to = "effectif", names_to = "indicateur") %>%
  ggplot(aes(x=Session,y=effectif,color=indicateur)) + geom_line() +
  facet_wrap(.~Filière, scales="free_y")
```


## Taux féminité

```{r, fig.asp=9/16}
iut %>%
  summarise(
    Taux.féminité = sum(Dont.effectif.des.candidates.admises) / sum(admis),
    .by=c(Session,Filière)) %>%
  arrange(Taux.féminité) %>% 
  mutate(Filière = factor(Filière,levels=unique(Filière))) %>%
  ggplot(aes(x=Session,y=Taux.féminité, color=Taux.féminité)) + 
  geom_line() +
  facet_wrap(.~Filière, scales="free_y") +
  scale_x_continuous(breaks = c(2020)) +
  scale_y_continuous(breaks = range, labels = ~ scales::percent(.x, accuracy = 1)) +
  scale_color_distiller(palette="RdBu", limits=c(0,1))
```

```{r}
iut.fem <- iut %>%
  summarise(
    Admises = sum(Dont.effectif.des.candidates.admises),
    .by=c(Session,Filière)) %>% View()
  arrange(Session) %>%
  summarise(
    Admises.diff = last(Admises) - first(Admises),
    .by=c(Filière) ) 

bind_rows(iut.fem, iut.fem %>% summarise(Admises.diff = sum(Admises.diff), Filière = "Total")) %>% 
  ggplot(aes(x=reorder(Filière,Admises.diff),y=Admises.diff)) + geom_col() +
  theme(axis.text.x = element_text(angle=90))
```


```{r}
iut.gen <- iut %>%
  summarise(
    Admis = sum(admis - Dont.effectif.des.candidates.admises),
    Admises = sum(Dont.effectif.des.candidates.admises),
    .by=c(Session,Filière)) %>%
  pivot_longer(c(Admis,Admises), values_to = "Admissions", names_to = "Genre") %>%
  arrange(Session) %>%
  summarise(
    Admissions.diff = last(Admissions) - first(Admissions),
    .by=c(Filière,Genre) ) 

bind_rows(iut.gen, iut.gen %>% summarise(Admissions.diff = sum(Admissions.diff), .by=Genre, Filière = "Total")) %>% 
  ggplot(aes(x=reorder(Filière,Admissions.diff),y=Admissions.diff,fill=Genre)) + geom_col() +
  theme(axis.text.x = element_text(angle=90))
```

## Taux même académie

```{r, fig.asp=9/16}
iut %>%
  summarise(
    Taux.meme_academie = sum(Dont.effectif.des.admis.issus.de.la.même.académie) / sum(admis),
    .by=c(Session,Filière)) %>%
  ggplot(aes(x=Session,y=Taux.meme_academie)) + geom_line() + facet_wrap(.~Filière, scales="free_y") +
  scale_x_continuous(breaks = c(2020)) +
  scale_y_continuous(breaks = range, labels = ~ scales::percent(.x, accuracy = 1))
```


## Taux boursiers

```{r, fig.asp=9/16}
iut %>%
  summarise(
    Taux.boursiers = sum(Dont.effectif.des.admis.boursiers.néo.bacheliers) / sum(admis),
    .by=c(Session,Filière)) %>%
  ggplot(aes(x=Session,y=Taux.boursiers)) + geom_line() + facet_wrap(.~Filière, scales="free_y") +
  scale_x_continuous(breaks = c(2020)) +
  scale_y_continuous(breaks = range, labels = ~ scales::percent(.x, accuracy = 1))
```



### Taux rétension

```{r}
iut.ret <- iut %>%
  filter(Session == max(Session)) %>%
  mutate(
   Taux.rétension = Rang.du.dernier.appelé.du.groupe.1+Rang.du.dernier.appelé.du.groupe.2 / places,
   Taux.rétension2 = (
     Effectif.des.candidats.en.terminale.professionnelle.ayant.reçu.une.proposition.d.admission.de.la.part.de.l.établissement +
     Effectif.des.candidats.en.terminale.générale.ayant.reçu.une.proposition.d.admission.de.la.part.de.l.établissement +
     Effectif.des.candidats.en.terminale.technologique.ayant.reçu.une.proposition.d.admission.de.la.part.de.l.établissement ) / places
  ) 

iut.ret %>%
  ggplot(aes(x=Taux.rétension, y=Taux.rétension2)) + geom_point() + geom_smooth()
```

```{r}
iut.ret %>%
  ggplot(aes(x=Taux.d.accès, y=Taux.rétension2)) + geom_point() + geom_smooth()
```


```{r}
iut.ret %>%
  ggplot(aes(x=Taux.sélection, y=Taux.rétension)) + geom_point() + geom_smooth()
```