---
title: "CPESR"
author: "CPESR"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(dplyr.summarise.inform = FALSE)
knitr::opts_chunk$set(fig.asp = 9/16, fig.retina = 2)

library(tidyverse)
library(ggcpesrthemes)
theme_set(theme_cpesr())
theme_cpesr_setup(authors = "Julien Gossa", source = "https://github.com/cpesr/RFC/")
```

## Données 

- [Source wikidata](https://query.wikidata.org/index.html#SELECT%20%3Funiv%20%3FunivLabel%20%3Fdebut%20%3Ffin%20%3Fpresident%20%3FpresidentLabel%20%3Fnaissance%20%3Fdeces%20%3Fage%20%3FsexeLabel%20%3FroleLabel%20%3FmotifLabel%20%0AWHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22fr%22.%20%7D%0A%20%20%0A%20%20%3Funiv%20wdt%3AP31%20wd%3AQ3551775%20.%20%23%20universit%C3%A9%20de%20France%0A%20%20%3Funiv%20p%3AP488%20%3Fnode%20.%20%20%20%20%20%20%20%20%23%20r%C3%A9cup%C3%A8re%20tous%20les%20pr%C3%A9sidents%20et%20pas%20seulement%20le%20dernier%0A%20%20%3Fnode%20ps%3AP488%20%3Fpresident%20.%20%0A%20%20OPTIONAL%20%7B%3Fnode%20pq%3AP1534%20%3Fmotif.%7D%0A%20%20OPTIONAL%20%7B%3Fnode%20pq%3AP39%20%3Frole.%7D%0A%20%20%0A%20%20OPTIONAL%7B%3Fnode%20pq%3AP580%20%3Fann%C3%A9e%20.%7D%20%23%20date%20de%20d%C3%A9but%20du%20mandat%0A%20%20OPTIONAL%7B%3Fnode%20pq%3AP582%20%3Fann%C3%A9e2%20.%7D%20%23%20date%20de%20fin%20du%20mandat%0A%20%20OPTIONAL%7B%3Fpresident%20wdt%3AP569%20%3Fann%C3%A9e3%20.%7D%20%23%20ann%C3%A9e%20de%20naissance%0A%20%20OPTIONAL%7B%3Fpresident%20wdt%3AP570%20%3Fann%C3%A9e4%20.%7D%20%23%20ann%C3%A9e%20de%20d%C3%A9c%C3%A8s%0A%20%20OPTIONAL%7B%3Fpresident%20wdt%3AP21%20%3Fsexe.%7D%20%23%20sexe%20du%20pr%C3%A9sident%0A%20%20%0A%20%20BIND(year(%3Fann%C3%A9e)%20as%20%3Fdebut)%20%23%20conserve%20que%20l'ann%C3%A9e%0A%20%20BIND(year(%3Fann%C3%A9e2)%20as%20%3Ffin)%0A%20%20BIND(year(%3Fann%C3%A9e3)%20as%20%3Fnaissance)%0A%20%20BIND(year(%3Fann%C3%A9e4)%20as%20%3Fdeces)%0A%20%20BIND(%3Fdebut%20-%20%3Fnaissance%20AS%20%3Fage)%20%23%20%C3%A2ge%20en%20d%C3%A9but%20de%20mandat%0A%7D%0A%0AORDER%20BY%20%3FunivLabel%20%3Fdebut)

```{r load}
prez <- read.csv("query.csv", dec='.') %>%
  filter(debut >= 1970) %>%
  mutate(décennie = as.character(floor(debut/10)*10)) %>%
  mutate(
    durée = fin-debut,
    age_début = debut - naissance,
    age_fin = fin - naissance) 

colnames(prez)
```

## Check

```{r, results='asis'}
prez %>%
  summarize(Nombre = n(), .by = presidentLabel) %>%
  filter(Nombre != 1) %>%
  spoiler_table("Multi prez")
```

```{r}
pprez <- prez %>%
  summarise(
    décennie = min(décennie),
    début = min(debut),
    fin = max(fin),
    durée = sum(durée),
    age_début = min(age_début),
    age_fin = max(age_fin),
    .by = presidentLabel
  )
```

## Explorations

```{r}
pprez %>%
  summarise(Nombre = n(), .by=durée) %>%
  ggplot(aes(x=durée,y=Nombre,fill=durée)) + geom_col(color="black",size=0.1) +
  scale_fill_distiller(palette="Blues",guide=FALSE, direction=0) +
  ylab("Nombre de président⋅es") +
  ggtitle("Durée des mandats de président⋅es d'université")
```



```{r}
pprez %>%
  filter(décennie != "2020") %>%
  summarise(durée_moyenne = mean(durée, na.rm=TRUE), .by=c(décennie)) %>%
  ggplot(aes(x=décennie,y=durée_moyenne,group="1")) + geom_line() + geom_point()
```

```{r}
pprez %>%
  summarise(Nombre = n(), .by = c(début, durée)) %>%
  ggplot(aes(x=début,y=durée,fill=Nombre)) + geom_smooth(color="grey", fill="grey") + geom_point(shape=21) +
  scale_fill_distiller(palette = "Reds", direction = 0)
```



```{r}
pprez %>%
  filter(décennie != "2020") %>%
  ggplot(aes(x=décennie,y=durée,fill=décennie)) + geom_boxplot() +
  scale_fill_brewer(palette="Blues", guide=FALSE) +
  ggtitle("Durée des mandats de président⋅es d'université") 
```


```{r}
pprez %>%
  summarise(Nombre = n(), .by = c(début, age_début)) %>%
  ggplot(aes(x=début,y=age_début,fill=as.character(Nombre))) + geom_smooth(color="grey", fill="grey") + geom_point(shape=21) +
  scale_fill_brewer(palette = "Reds")
```

```{r}
prez %>%
  ggplot(aes(x=décennie,y=age_début)) + geom_boxplot()
```



```{r}
pprez %>%
  ggplot(aes(x=début,y=age_début)) + geom_smooth() + geom_point() 
```

```{r}
prez %>%
  ggplot(aes(x=décennie,y=age_fin)) + geom_boxplot() 
```

```{r}
prez %>%
  ggplot(aes(x=debut,y=age_fin)) + geom_smooth() + geom_point() 
```


```{r}
prez %>%
  pivot_longer(c(age_début,age_fin), values_to = "Valeur", names_to = "Age") %>%
  ggplot(aes(x=décennie,y=Valeur,fill=Age)) + geom_boxplot() +
  ylab("âge") +
  ggtitle("Age au début et à la fin des mandats de président⋅es d'universités")
```


```{r}
prez %>%
  rename(sexe=sexeLabel) %>%
  summarise(Nombre = n(), .by=c(sexe,décennie)) %>%
  mutate(Part = Nombre / sum(Nombre), .by = c(décennie)) %>%
  ggplot(aes(x=décennie,y=Part,color=sexe, group=sexe)) + 
  geom_line(size=1) + geom_point(shape=21,size=2,stroke=1.5,fill="white") +
  scale_y_continuous(labels = scales::percent) +
  ggtitle("Part des président⋅es d'université par sexe")
  
```
