---
title: "BIATSS"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.asp=9/16, fig.retina = 2)
library(tidyverse)
library(ggcpesrthemes)

theme_cpesr_setup(authors = "Julien Gossa", source="SIES https://data.enseignementsup-recherche.gouv.fr/explore/dataset/fr-esr-personnels-biatss-etablissements-publics/")

biatss <- read.csv2("../data/fr-esr-personnels-biatss-etablissements-publics.csv")
```

Source : https://data.enseignementsup-recherche.gouv.fr/explore/dataset/fr-esr-personnels-biatss-etablissements-publics/export/

```{r biatss.cn}
colnames(biatss)
```



```{r biatss.eff}
biatss %>%
  group_by(Année,Type.de.personnel) %>%
  summarise(Effectif = sum(Effectif)) %>%
  ggplot(aes(x=Année,y=Effectif, group=Type.de.personnel, color=Type.de.personnel)) +
  geom_line() + geom_point() +
  expand_limits(y=0) +
  theme_cpesr_cap()
```


```{r biatss.tt}
biatss %>%
  group_by(Année,Type.de.personnel) %>%
  summarise(Effectif = sum(Effectif)) %>%
  ungroup() %>%
  pivot_wider(values_from = Effectif, names_from = Type.de.personnel) %>%
  mutate(Taux.de.titularité = titulaires / (titulaires+contractuels)) %>%
  ggplot(aes(x=Année,y=Taux.de.titularité, group=1)) +
  geom_line() + geom_point() +
  expand_limits(y=c(0.55,0.65)) +
  theme_cpesr_cap()
```


```{r biatss.tt.type}
biatss %>%
  group_by(Année,etablissement_type,Type.de.personnel) %>%
  summarise(Effectif = sum(Effectif)) %>%
  ungroup() %>%
  pivot_wider(values_from = Effectif, names_from = Type.de.personnel) %>%
  mutate(Taux.de.titularité = titulaires / (titulaires+contractuels)) %>%
  ggplot(aes(x=Année,y=Taux.de.titularité, group=etablissement_type, color=etablissement_type)) +
  geom_line() + geom_point() +
  expand_limits(y=c(0.3,0.7)) +
  theme_cpesr_cap() +
  scale_color_discrete(name="")
```

```{r biatss.tt.cat}
biatss %>%
  group_by(Année,Catégorie,Type.de.personnel) %>%
  summarise(Effectif = sum(Effectif)) %>%
  ungroup() %>%
  pivot_wider(values_from = Effectif, names_from = Type.de.personnel) %>%
  mutate(Taux.de.titularité = titulaires / (titulaires+contractuels)) %>%
  ggplot(aes(x=Année,y=Taux.de.titularité, group=Catégorie, color=Catégorie)) +
  geom_line() + geom_point() +
  expand_limits(y=c(0.3,0.7)) +
  theme_cpesr_cap() +
  scale_color_discrete(name="")
```


```{r biatss.eff.cat}
biatss %>%
  mutate(Type.de.personnel = fct_rev(Type.de.personnel)) %>%
  group_by(Année,Catégorie,Type.de.personnel) %>%
  summarise(Effectif = sum(Effectif)) %>%
  ggplot(aes(x=Année,y=Effectif, group=paste(Catégorie,Type.de.personnel), color=Catégorie, shape=Type.de.personnel, linetype=Type.de.personnel)) +
  geom_line() + geom_point() +
  expand_limits(y=c(0.3,0.7)) +
  theme_cpesr_cap() +
  scale_color_discrete(name="")
```



```{r biatss.tt.univ}
biatss %>%
  filter(etablissement_type=="Université", Année==2020) %>%
  group_by(Année,Etablissement,Type.de.personnel) %>%
  summarise(Effectif = sum(Effectif)) %>%
  ungroup() %>%
  pivot_wider(values_from = Effectif, names_from = Type.de.personnel) %>%
  mutate(Taux.de.titularité = titulaires / (titulaires+contractuels)) %>%
  ggplot(aes(x=titulaires,y=contractuels, color=Taux.de.titularité)) +
  geom_point() + ggrepel::geom_text_repel(aes(label=Etablissement)) +
  geom_smooth(method = "lm", alpha=0.6, size=0.2) +
  scale_color_distiller(palette="RdBu", direction = 0) +
  theme_cpesr_cap() + theme_minimal()
```

```{r biatss.tt.univ.ht}
biatss %>%
  filter(etablissement_type=="Université", Année==2020) %>%
  group_by(Année,Etablissement,Type.de.personnel) %>%
  summarise(Effectif = sum(Effectif)) %>%
  ungroup() %>%
  pivot_wider(values_from = Effectif, names_from = Type.de.personnel) %>%
  mutate(Taux.de.titularité = titulaires / (titulaires+contractuels)) %>%
  arrange(Taux.de.titularité) %>%
  psych::headTail(top = 10, bottom = 10) %>%
  kableExtra::kable()
```


```{r biatss.fil}
biatss %>%
  group_by(Année,Filière=code_filiere) %>%
  summarise(Effectif = sum(Effectif)) %>%
  ggplot(aes(x=Année,y=Effectif, group=Filière, color=Filière)) +
  geom_line() + geom_point() +
  theme_cpesr_cap() +
  guides(color=guide_legend(nrow=2,byrow=TRUE))
```

```{r biatss.corps}
biatss %>%
  filter(Année %in% range(Année)) %>%
  mutate(Année = as.character(Année)) %>%
  group_by(Année,Corps=Corps) %>%
  summarise(Effectif = sum(Effectif)) %>%
  ggplot(aes(y=reorder(Corps,Effectif),x=Effectif, group=Année, fill=Année)) +
  geom_col(position="dodge") +
  theme_cpesr_cap() +
  guides(color=guide_legend(nrow=2,byrow=TRUE)) +
  ylab("") + theme_minimal()
```

```{r biatss.corps.log}
biatss %>%
  filter(Année %in% range(Année)) %>%
  mutate(Année = as.character(Année)) %>%
  group_by(Année,Corps=Corps) %>%
  summarise(Effectif = sum(Effectif)) %>%
  ggplot(aes(y=reorder(Corps,Effectif),x=Effectif, group=Année, fill=Année)) +
  geom_col(position="dodge") +
  theme_cpesr_cap() +
  guides(color=guide_legend(nrow=2,byrow=TRUE)) +
  ylab("") + theme_minimal() +
  scale_x_log10()
```


```{r biatss.bap}
biatss %>%
  filter(Année %in% range(Année)) %>%
  mutate(Année = as.character(Année)) %>%
  group_by(Année,bap=paste(code_bap,BAP)) %>%
  summarise(Effectif = sum(Effectif)) %>%
  filter(bap!=" ") %>%
  ggplot(aes(y=reorder(bap,Effectif),x=Effectif, group=Année, fill=Année)) +
  geom_col(position="dodge") +
  theme_cpesr_cap() +
  guides(color=guide_legend(nrow=2,byrow=TRUE)) +
  ylab("") + theme_minimal()
```


```{r biatss.bap.ul}
biatss %>%
  filter(Etablissement == "Université de Lorraine") %>%
  filter(Année %in% range(Année)) %>%
  mutate(Année = as.character(Année)) %>%
  group_by(Année,bap=paste(code_bap,BAP)) %>%
  summarise(Effectif = sum(Effectif)) %>%
  filter(bap!=" ") %>%
  ggplot(aes(y=reorder(bap,Effectif),x=Effectif, group=Année, fill=Année)) +
  geom_col(position="dodge") +
  theme_cpesr_cap() +
  guides(color=guide_legend(nrow=2,byrow=TRUE)) +
  ylab("") + theme_minimal()
```




```{r biatss.medecin}
biatss %>%
  filter(code_corps %in% c("MED PREV","MEN", "INF - B","INF - A")) %>%
  group_by(Année, Corps) %>%
  summarise(Effectif = sum(Effectif)) %>%
  ggplot(aes(x=Année,y=Effectif, group=Corps, color=Corps)) +
  geom_line() + geom_point() +
  expand_limits(y=0) +
  theme_cpesr_cap() +
  ggtitle("Effectif médecins et infirmiers dans l'ESR") +
  guides(color=guide_legend(nrow=2,byrow=TRUE))

```



```{r biatss.medecin.tot}
biatss %>%
  filter(code_corps %in% c("MED PREV","MEN", "INF - B","INF - A")) %>%
  group_by(Année) %>%
  summarise(Effectif = sum(Effectif)) %>%
  ggplot(aes(x=Année,y=Effectif, group=1)) +
  geom_line() + geom_point() +
  expand_limits(y=0) +
  theme_cpesr_cap() +
  ggtitle("Effectif médecins et infirmiers dans l'ESR")
```


```{r biatss.medecin.region}
biatss %>%
  filter(code_corps %in% c("MED PREV","MEN", "INF - B","INF - A")) %>%
  filter(Année == 2020) %>%
  group_by(Année, Région, Corps=code_corps) %>%
  summarise(Effectif = sum(Effectif)) %>%
  ungroup() %>%
  pivot_wider(names_from = Corps, values_from = Effectif) %>%

  kableExtra::kable()
```

## Statuts

```{r, results='asis'}
biatsscat <- function(var) {
  biatss %>%
    filter(Année == max(Année)) %>%
    summarise(
      Effectif = sum(Effectif),
      Femmes = sum(effectif_femmes),
      .by = !!sym(var)) %>%
    arrange(!!sym(var)) %>%
    spoiler_table(var, trim = Inf)
}

biatsscat("Type.de.personnel")
biatsscat("Catégorie")
biatsscat("Corps")
biatsscat("Filière")
biatsscat("BAP")
```

### Statuts Université de Strasbourg

```{r, results='asis'}
biatss %>%
  filter(Etablissement == "Université de Strasbourg", Année == max(Année)) %>%
  summarise(
    Effectif = sum(Effectif),
    Femmes = sum(effectif_femmes),
    .by = c(Type.de.personnel,Catégorie,Corps,code_corps,Filière,code_filiere,BAP,code_bap)
  ) %>%
  pivot_wider(names_from = Type.de.personnel, values_from = c(Effectif,Femmes)) %>%
  arrange(Catégorie,Corps,Filière,BAP) %>%
  spoiler_table("Unistra", trim = Inf)
```
