---
title: "H2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.retina = 2, fig.asp = 9/16)
library(tidyverse)
library(ggcpesrthemes)

theme_set(theme_cpesr())
theme_cpesr_setup(authors = "Julien Gossa", source = "https://github.com/cpesr/RFC/blob/main/H2020/H2020.md")

h2020 <- read.csv2("appels-a-projets-horizon-2020-projets-retenus-et-participants-identifies0.csv", dec='.')
```

Source : https://data.enseignementsup-recherche.gouv.fr/explore/dataset/appels-a-projets-horizon-2020-projets-retenus-et-participants-identifies0/export/

```{r colname}
colnames(h2020)
```

## Total des financements par pays

```{r country, results='asis'}
df <- h2020 %>%
  group_by(country_name) %>%
  summarise(funding = sum(funding)) %>%
  arrange(desc(funding)) %>%
  mutate(funding = round(funding/10e6,2))

sorted_cn <- df$country_name

df %>% ggcpesrthemes::spoiler_table()
```

```{r country.plot}
h2020 %>%
  group_by(country_name) %>%
  summarise(funding = sum(funding)) %>%
  arrange(desc(funding)) %>%
  mutate(funding = round(funding/10e6,2)) %>%
  head(10) %>%
  ggplot(aes(y=reorder(country_name,funding),x=funding)) +
  geom_col()
```


## Total des financements par type de participant

```{r participant_type_name}
h2020 %>%
  group_by(participant_type_name) %>%
  summarise(funding = sum(funding)) %>%
  arrange(desc(funding)) %>%
  mutate(funding = round(funding/10e6,2)) %>%
  kableExtra::kable()
```

```{r participant_type_name.plot}
h2020 %>%
  group_by(participant_type_name) %>%
  summarise(funding = sum(funding)) %>%
  arrange(desc(funding)) %>%
  mutate(funding = round(funding/10e6,2)) %>%
  head(10) %>%
  ggplot(aes(y=reorder(participant_type_name,funding),x=funding)) +
  geom_col()
```




## Total des financements par type de participant et par pays.

```{r country_participant_type_name, results='asis'}
h2020 %>%
  mutate(country_name = factor(country_name, levels = sorted_cn)) %>%
  group_by(country_name, participant_type_name) %>%
  summarise(funding = sum(funding)) %>%
  arrange(country_name, funding) %>%
  mutate(funding = round(funding/10e6,2)) %>%
  spoiler_table()
```

```{r country_name_participant_type_name}
h2020 %>%
  mutate(country_name = factor(country_name, levels = rev(sorted_cn))) %>%
  filter(country_name %in% head(sorted_cn, 10)) %>%
  group_by(country_name, participant_type_name) %>%
  summarise(funding = sum(funding)) %>%
  mutate(funding = round(funding/10e6,2)) %>%
  ggplot(aes(y=country_name,x=funding,fill=participant_type_name)) +
  geom_col()
```


## Total des financements par type de participant et par année

```{r participant_type_name_year}
h2020 %>%
  group_by(start_year = str_sub(start_date,1,4), participant_type_name) %>%
  summarise(funding = sum(funding)) %>%
  #mutate(funding = round(funding/10e6,2)) %>%
  ggplot(aes(x=start_year,y=funding,fill=participant_type_name, group=participant_type_name)) +
  geom_area()
```


## Comparaisons


```{r country_participant_type_name.ratio}
h2020 %>%
  mutate(country_name = factor(country_name, levels = rev(sorted_cn))) %>%
  filter(country_name %in% head(sorted_cn, 10)) %>%
  group_by(country_name, participant_type_code) %>%
  summarise(funding = sum(funding)) %>%
  group_by(country_name) %>% 
  mutate(ratio = funding / sum(funding)) %>%
  filter(participant_type_code %in% c("Org. privés","Ens. supérieur","Recherche")) %>%
  ggplot(aes(y=reorder(country_name,ratio,FUN=first),x=ratio,fill=participant_type_code)) +
  geom_col() +
  facet_grid(.~participant_type_code) +
  ylab("") +
  scale_x_continuous(labels=scales::percent) +
  ggtitle("Répartition des subventions H2020 par type de participant", "pour les 10 pays ayant reçu le plus de financements") +
  theme(legend.position = "None") +
  cpesr_cap()
```

## Nombre de partenaires

```{r part.nb}
part.nb <- h2020 %>%
  mutate(country_name = factor(country_name, levels = rev(sorted_cn))) %>%
  filter(country_name %in% head(sorted_cn, 10)) %>%
  select(country_name,participation_id,participant_type_code) %>%
  #unique() %>%
  group_by(country_name,participation_id) %>%
  summarize(n = n()) 
  #summarize(participans = paste(participant_type_code))

part.nb %>%
  group_by(country_name) %>%
  summarise(
    moyenne = mean(n)
  ) %>% 
  arrange(desc(moyenne)) %>%
  kableExtra::kable()
```



```{r part.nb.plot}
part.nb %>%
  ggplot(aes(y=country_name, x=n)) +
  geom_boxplot() +
  ylab("") + xlab("Nombre de participants") +
  ggtitle("Nombre de participants aux projets H2020","Top 10 des pays les plus financés") +
  theme(legend.position = "None") +
  cpesr_cap()
```


## Participation univ

```{r part.type.nb}
part.type.nb <- h2020 %>%
  mutate(country_name = factor(country_name, levels = rev(sorted_cn))) %>%
  filter(country_name %in% head(sorted_cn, 10)) %>%
  filter(participant_type_code != "") %>%
  group_by(country_name, participation_id) %>%
  mutate(nb_participants=n()) %>%
  group_by(country_name, participation_id, nb_participants, participant_type_code) %>%
  summarize(nt = n()) %>%
  pivot_wider(names_from = participant_type_code, values_from = nt, values_fill = 0)

part.type.nb.esr <- part.type.nb %>%
  mutate(
    es = `Ens. supérieur` != 0,
    multi_participants = ifelse(nb_participants > 1, "multi participants", "mono participant")) %>%
  group_by(country_name, multi_participants, es) %>%
  summarise(nb_participations = n()) %>%
  group_by(country_name, multi_participants) %>%
  mutate(ratio = nb_participations / sum(nb_participations)) %>%
  filter(es) %>%
  select(-es)

part.type.nb.esr %>%
  arrange(country_name) %>%
  kableExtra::kable()
```



```{r part.type.nb.esr.plot}
part.type.nb.esr %>%
  ggplot(aes(y=country_name,x=ratio,fill=multi_participants)) +
  geom_col() +
  facet_grid(.~multi_participants) +
  scale_x_continuous(labels=scales::percent) +
  ylab("") +
  ggtitle("Taux de participation de l'enseignement supérieur aux projets H2020", "selon que le projet est mono ou multi participant, top 10 des pays les plus financés") +
  theme(legend.position = "None") +
  cpesr_cap()
```


## Participation privé

```{r part.type.nb.prive}
part.type.nb.prive <- part.type.nb %>%
  mutate(
    es = `Org. privés` != 0,
    multi_participants = ifelse(nb_participants > 1, "multi participants", "mono participant")) %>%
  group_by(country_name, multi_participants, es) %>%
  summarise(nb_participations = n()) %>%
  group_by(country_name, multi_participants) %>%
  mutate(ratio = nb_participations / sum(nb_participations)) %>%
  filter(es) %>%
  select(-es)

part.type.nb.prive %>%
  arrange(country_name) %>%
  kableExtra::kable()
```



```{r part.type.nb.prive.plot}
part.type.nb.prive %>%
  ggplot(aes(y=country_name,x=ratio,fill=multi_participants)) +
  geom_col() +
  facet_grid(.~multi_participants) +
  scale_x_continuous(labels=scales::percent) +
  ylab("") +
  ggtitle("Taux de participation des organismes privés aux projets H2020", "selon que le projet est mono ou multi participant, top 10 des pays les plus financés") +
  theme(legend.position = "None") +
  cpesr_cap()
```


## Fundings

```{r fund.type.nb}
funding.type <- h2020 %>%
  mutate(country_name = factor(country_name, levels = rev(sorted_cn))) %>%
  filter(country_name %in% head(sorted_cn, 10)) %>%
  filter(participant_type_code != "") %>%
  group_by(country_name, participation_id, participant_type_code) %>%
  summarise(funding = sum(funding)) %>%
  group_by(country_name, participation_id) %>%
  mutate(part = funding / sum(funding)) %>% 
  filter(part != 1) %>%
  group_by(country_name, participant_type_code) %>%
  summarise(funding_moyen = mean(funding), 
            part_moyenne = mean(part))


funding.type %>% 
  mutate(part_moyenne = scales::percent(part_moyenne)) %>%
  kableExtra::kable()
```


```{r fund.type.plot}
funding.type %>%
  filter(participant_type_code %in% c("Org. privés","Ens. supérieur","Recherche")) %>%
  ggplot(aes(y=country_name,x=part_moyenne,fill=participant_type_code)) +
  geom_col() +
  facet_grid(.~participant_type_code) +
  scale_x_continuous(labels=scales::percent) +
  ylab("") +
  ggtitle("Part moyenne du financement dans les projets multi-partenaires", "par type de partenaire, aux projets H2020, top 10 des pays les plus financés") +
  theme(legend.position = "None") +
  cpesr_cap()
```


