---
title: "Data étudiants"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

read.etu <- function() {

  etu <- read.table("fr-esr-statistiques-sur-les-effectifs-d-etudiants-inscrits-par-etablissement.csv",
                    header=TRUE, sep=';', quote='"') %>%
    mutate(
      UAI = ETABLISSEMENT,
      Rentrée = as.factor(RENTREE),
      kpi.ETU.P.effectif = Nombre.d.étudiants.inscrits..inscriptions.principales..hors.doubles.inscriptions.CPGE,
      kpi.ETU.S.cycle.1.L = Cycle.universitaire..cursus.LMD....L..1er.cycle.-(Nombre.d.étudiants.inscrits..inscriptions.principales..y.compris.doubles.inscriptions.CPGE-kpi.ETU.P.effectif),
      kpi.ETU.S.cycle.2.M = Cycle.universitaire..cursus.LMD....M..2ème.cycle.,
      kpi.ETU.S.cycle.3.D = Cycle.universitaire..cursus.LMD....D..3ème.cycle.,
      #kpi.ETU.S.diplome.national = Type.de.diplôme...Diplômes.nationaux,
      kpi.ETU.S.diplomeEtablissement = Type.de.diplôme...Diplômes.d.établissement
  )
}

etu <- read.etu()
```

## Description des données

- source : https://data.enseignementsup-recherche.gouv.fr/explore/dataset/fr-esr-statistiques-sur-les-effectifs-d-etudiants-inscrits-par-etablissement/information/
- variables : 
```{r colnames}
colnames(etu)
```


